### ISSUE TITLE
Gostaria de uma ajuda

### ISSUE THREAD

**Issue by alphabraga** [andersondanilo/CnabPHP#1]
Olá!

Também estou criando uma lib para gerar remessas e ler os retornos....

Estou com um problema, talvez vc saiba a solução. Você esta utilizando algum caracter especial para finalizar o arquivo de remessa? Estou tentando validar uma remessa de teste para o Bradesco. E eles estão me pedindo esse carcter de fechamento do arquivo.....

**Comment by leopucci** [comment]
@andersondanilo, tudo certinho?

Cara estava olhando seu projeto e fiquei procurando como fazer doc/ted, pagar imposto pelas classes php, mas se eu entendi o cod e a wiki este codigo por hora só faz cobranca, boleto?
To certo no pensamento?

Valeu

**Comment by andersondanilo** [comment]
Ele foi feito pensando no boleto, mas segue toda a documentação do CNAB.

Parece interessante, eu ainda não sabia desta possibilidade de efetuar
pagamentos através do Cnab.

Em 2 de outubro de 2015 17:00, Leonardo Pucci <notifications@github.com>
escreveu:

**Comment by leopucci** [comment]
Tem sim, da pra fazer tudo, o problema é que ele te cobra por cada transação. (Achei meio caro)
http://download.itau.com.br/bankline/SISPAG_CNAB.pdf

Uma outra duvida, quando voce trabalha com o banco, voce gera o arquivo e faz upload pelo site, depois faz download no site ? (um processo manual?) Ou tem alguma forma de se conectar no banco e trabalhar direto sem interação manual?

**Comment by andersondanilo** [comment]
Não, gero o arquivo e faço o upload manualmente. Ainda não achei uma forma de automatizar este processo.
