### ISSUE TITLE
Remessa de Pagamento

### ISSUE THREAD

**Issue by RenantDev** [andersondanilo/CnabPHP#112]
Prezados, bom dia!
Estou precisando gerar um arquivo de remessa para agendamento do pagamento de fornecedores na Caixa no layout CNAB240.
É possível gerar esse tipo de arquivo de remessa com esse script?

**Comment by marcelozanatta** [comment]
Opa!
Sim ele gera os arquivos de remessa. Fiz isso esses dias
Porem depois de gerado valida no sistema que a caixa disponibiliza pra validar o arquivo de remessa.
No meu caso CNAB240 gerou alguns erros por falta do caractere vazio " ".
Quero ver no código o porque disso ter acontecido.... Se eu encontrar posto a solução.

**Comment by RenantDev** [comment]
Se você postar vai me ajudar bastante.
Seria legal ter um exemplo na documentação aqui do repositório.
Vou dar uma estudada no arquivo de teste. 
vlw @marcelozanatta
