### ISSUE TITLE
"Error in field 'agencia_dv': value 'X' dont is a number, need format 9(1)"

### ISSUE THREAD

**Issue by Fertusco** [andersondanilo/CnabPHP#115]
Boa noite.

Estou tentando realizar a geração da remessa utilizando o banco do brasil, porém está retornando o seguinte erro:

> "Error in field 'agencia_dv': value 'X' dont is a number, need format 9(1)"

Já abri o arquivo como mencionado em post anterior para alteração do picture (andersondanilo/cnab_yaml/cnab240/001/remessa/detalhe_segmento_p.yml), porém neste arquivo não consta agencia_dv.

Poderiam me ajudar?

**Comment by almando** [comment]
Esta variável esta no arquivo cnab240/001/header_arquivo.yml.
Já existe um pull request que um amigo meu fez a correção deste, no projeto andersondanilo/cnab_yaml.

**Comment by Fertusco** [comment]
Prezado @almando, na verdade não é este arquivo na pasta 001. Este arquivo não possui a variável agencia_dv.

O arquivo que responde por esta variável esta na pasta generic, consegui resolver a questão.

Muito obrigado pela ajuda.
