### ISSUE TITLE
Cadê o arquivo autoload.php ?

### ISSUE THREAD

**Issue by rafso** [andersondanilo/CnabPHP#130]
Não estou localizando o arquivo autoload.php que está descrito no exemplo de geração de remessa:
https://github.com/andersondanilo/CnabPHP/wiki/Criando-um-arquivo-de-remessa

Em qual arquivo devo dar o include?

**Comment by DelBianco** [comment]
Você usou o composer para instalar o repositório como diz o tutorial?

`composer require andersondanilo/cnab_php`

se não tiver o composer instalado na sua máquina/servidor utilize no ubuntu
`sudo apt install composer`

ou pelo site [https://getcomposer.org/download/](https://getcomposer.org/download/)

**Comment by rafso** [comment]
usei não, fiz só um clone do projeto pelo git, vlw
