### ISSUE TITLE
Erro em um if no CnabPHP/src/Cnab/Remessa/Cnab240/Arquivo.php

### ISSUE THREAD

**Issue by nandodutra** [andersondanilo/CnabPHP#15]
Olá, fiz um fork do CnabPHP para implementar o suporte ao Sicoob. Deem uma olhada na linha 95 do arquivo "CnabPHP/src/Cnab/Remessa/Cnab240/Arquivo.php", se não estou enganado nessa linha deveria ser uma verificação de valores e não uma atribuição.

Desde já obrigado!

**Comment by andersondanilo** [comment]
Foi corrigido no commit de filpgame

**Comment by andersondanilo** [comment]
https://github.com/andersondanilo/CnabPHP/commit/ab9cbeda9791928606e690277acd58bbe123d6d8
