### ISSUE TITLE
erro ao validar remessa itau CNAB 400

### ISSUE THREAD

**Issue by AleHHHG** [andersondanilo/CnabPHP#20]
Ao validar o layout do arquivo de remessa ele me retorno essa mensagem.

Registro: detalhe
Linha: 2
Posição 001 - Campo: Identificação do Registro - Conteúdo fixo difere do esperado. (2)

O que deve ser feito?

**Comment by andersondanilo** [comment]
Olá Ale,

Qual versão você está utilizando? dev-master?

Caso sim, você pode enviar o arquivo gerado para o meu email: contato @ andersondanilo.com

**Comment by AleHHHG** [comment]
Ok, Andreson

Te enviei o arquivo.

Obrigado

**Comment by s4muca** [comment]
@andersondanilo qual foi a solução?

**Comment by andersondanilo** [comment]
A documentação em que me tinha como base considerava uma linha extra para a multa, porém na documentação disponibilizada online (de 2012) e o itaú não estava aceitando o mesmo, portanto foi removido. (a multa deverá ser configurada com o gerente da conta).
