### ISSUE TITLE
Código do Cedente na caixa

### ISSUE THREAD

**Issue by gabrielqs** [andersondanilo/CnabPHP#21]
Oi Anderson,

Antes de qualquer coisa, parabéns pela iniciativa.

Esta linha com o código do cedente está travando a geração de arquivos de remessa CEF, veja (Cnab_Remessa_Cnab400_Arquivo):

        if($this->codigo_banco == Cnab_Banco::CEF)
        {
            $this->header->codigo_cedente = $this->configuracao['codigo_cedente'];
        }
        else
        {
            $this->header->agencia = $this->configuracao['agencia'];
            $this->header->conta = $this->configuracao['conta'];
            $this->header->conta_dv = $this->configuracao['conta_dac'];
        }

Este campo não existe no header do yaml genérico. Qual era a sua intenção aqui?

Abs,
Gabriel

**Comment by andersondanilo** [comment]
O Suporte à remessa Cnab400 da caixa está incompleto

**Comment by andersondanilo** [comment]
O tutorial do README estava desatualizado.

Segue novo:
https://github.com/andersondanilo/CnabPHP/wiki/Criando-um-arquivo-de-remessa
