### ISSUE TITLE
Arquivo de remessa não esta sendo gerado

### ISSUE THREAD

**Issue by willmkt** [andersondanilo/CnabPHP#26]
Ola,

Estou tentando gerar o arquivo de remessa como esta o exemplo na wiki, mas o arquivo não gera.

Obs: Estou tentando gerar para o Banco do Brasil, tem suporte?

**Comment by andersondanilo** [comment]
Ainda não temos suporte para a remessa, mas caso você queira o suporte mande um request que eu irei analisar.
