### ISSUE TITLE
Registro 1 Inválido

### ISSUE THREAD

**Issue by ewertoncode** [andersondanilo/CnabPHP#28]
Bom dia Anderson!

Primeiramente parabéns pela biblioteca, é de grande ajuda!

Cara, tô gerando remessa para o Itaú, e tá me retornando o seguinte aviso:
Aviso: Tamanho do Registro 1 Invalido

Saberia me dizer pq está ocorrendo?

Obrigado!

**Comment by ewertoncode** [comment]
Esta mensagem era devido o cadastro não está devidamente completo junto ao banco.

Resolvido.

**Comment by phcmaia** [comment]
Estou com o mesmo problema amigo , vc poderia explicar com mais detalhes oq aconteceu ?

**Comment by ewertoncode** [comment]
Vc precisa verificar com o gerente se sua conta está devidamente habilitado a geração de boletos e se os dados estão corretos. ;)
