### ISSUE TITLE
Dúvida sobre a remessa

### ISSUE THREAD

**Issue by emptydrawer** [andersondanilo/CnabPHP#31]
Bom dia,

O usuário é que deve incluir o arquivo de remessa no software do banco ou o software já envia diretamente para o banco? Se a resposta é "não", existe como fazer isso?

Desde já agradeço

**Comment by andersondanilo** [comment]
Olá Sr. Empty Drawer,

O usuário deve enviar a remessa para o banco manualmente.

Até onde eu sei não é possível enviar para o banco, desconheço qualquer api ou método de integração que seja capaz de fazer isso.

**Comment by emptydrawer** [comment]
Obrigado!

Cordialmente,

Paulo Henrique Luz

Em 21 de janeiro de 2016 19:29, Anderson Danilo <notifications@github.com>
escreveu:
