### ISSUE TITLE
Remessa Sicoob (Caixa) CNAB240

### ISSUE THREAD

**Issue by PedroFagundes** [andersondanilo/CnabPHP#32]
Ola Anderson, tranquilo? Estou tentando gerar um arquivo remessa CNAB240 com o layout da CEF porém estou tendo problemas na geração do mesmo. Configurei os "campos extras" que são necessários para esse Layout porém após configurar o campo **agencia_mais_cedente_dv **a função de validação lança um InvalidArgumentException. Setei os valores "8"(string) e 8(numerico) manualmente no campo porém o problema persiste. Nos campos que são utilizados para calcular o valor do **agencia_mais_cedente_dv**, utilizei os valores que foram utilizados por você no exemplo de calculo do campo. 

Obrigado desde já.

**Comment by Suhdo** [comment]
@PedroFagundes Eu estou fazendo o mesmo para cef/sigcb e obtive os mesmo erro. 
Eu não entendi bem a classe ainda mas mexi um pouco em Cnab/Remessa/Cnab240/Arquivo.php

Eu declarei o indice 
`$campos[] = 'agencia_mais_cedente_dv';`

Declarei na matriz do header do arquivo
`$this->headerArquivo->agencia_mais_cedente_dv = $this->configuracao['agencia_mais_cedente_dv'];`

Setei a variável com o valor vindo da configuracão
`$detalhe->segmento_p->agencia_mais_cedente_dv = $this->headerArquivo->agencia_mais_cedente_dv;`

Este erro eu resolvi assim, não sei fiz certo, mas o script prosseguiu a execução e começõu a montar o arquivos. Porém não consigo criar e salvar, me retorna o erro

`Fatal error: Uncaught exception 'InvalidArgumentException' in /public_html/src/Cnab/Remessa/Cnab240/Arquivo.php:318 Stack trace: #0 /public_html/src/Cnab/Remessa/Cnab240/Arquivo.php(368): Cnab\Remessa\Cnab240\Arquivo->getText() #1 /public_html/src/boleto/remessa_caixa_sigcb.php(191): Cnab\Remessa\Cnab240\Arquivo->save('/home/storage/5...') #2 /public_html/src/boleto/remessa.php(16): include('/home/storage/5...') #3 {main} thrown in /home/storage/5/54/03/passodeartsuhdo/public_html/suhdo/src/Cnab/Remessa/Cnab240/Arquivo.php on line 318`

Alguma sugestão? Posta a sequência do seu header aí, valeu. 
Desde já obrigado.

**Comment by PedroFagundes** [comment]
@Suhdo eu nao tinha muito tempo para debugar o código então fiz na mão rsrsrs
mandei hoje para homologação no banco, caso esteja tudo correto, posto o snippet aqui. 

Abraço

**Comment by Suhdo** [comment]
Blz isso seria uma grande ajuda, vou continuar estudando as classes pra ver se consigo resolver.
Abraço.

**Comment by PedroFagundes** [comment]
@Suhdo Cara, estou sem tempo pra aprimorar o código mas o que vale é que funciona hehehe se ainda estiver precisando....

`<?php
    $data = new DateTime();
    $headerArquivo = array(
        // CONTROLE
        'banco'             => '756', // Código do Sicoob na Compensação: "756"
        'lote'              => '0000', // Lote de Serviço: "0000"
        'registro'          => '0', // Tipo de Registro: "0"
        // CNAB
        'CNAB_1'            => '', // Uso Exclusivo FEBRABAN / CNAB: Brancos
        // EMPRESA
        'tipo_inscricao'    => '2' , // Tipo de Inscrição da Empresa: '1'  =  CPF '2'  =  CGC / CNPJ
        'num_inscricao'     => '19082178000157', //Número de Inscrição da Empresa
        'convenio'          => '', //Código do Convênio no Sicoob: Brancos
        'agencia'           => '41033', // Prefixo da Cooperativa (5 digitos)
        'agencia_dv'        => '3', // Dígito Verificador do Prefixo (1 digito)
        'conta'             => '3683-8', // Conta Corrente
        'conta_dv'          => '8', // Dígito Verificador da Conta
        'dv'                => '', // Dígito Verificador da Ag/Conta: Brancos
        'nome_empresa'      => 'FUNERARIA RENASCER DIAMANTINA', // Nome da Empresa
        //  BANCO
        'nome_banco'        => 'SICOOB', // Nome do Banco: SICOOB
        // CNAB
        'CNAB_2'            => '', // Uso Exclusivo FEBRABAN / CNAB: Brancos
        // ARQUIVO
        'codigo_remessa'    => '1', // Código Remessa / Retorno: "1"
        'data_geracao'      => $data->format('dmY'), // Data de Geração do Arquivo
        'hora_geracao'      => $data->format('His'), // Hora de Geração do Arquivo
        'sequencial'        => '000001', // Número Seqüencial do Arquivo: Número seqüencial adotado e controlado pelo responsável pela geração do arquivo para ordenar a disposição dos arquivos encaminhados. Evoluir um número seqüencial a cada header de arquivo.
        'versao_layout'     => '081', // No da Versão do Layout do Arquivo: "081"
        'densidade'         => '00000', // Densidade de Gravação do Arquivo: "00000"
        // RESERVADOS
        'reservado_branco'  => '', // Para Uso Reservado do Banco: Brancos
        'reservado_empresa' => '', // Para Uso Reservado da Empresa: Brancos
        // CNAB
        'CNAB_3'            => '', //Uso Exclusivo FEBRABAN / CNAB: Brancos
    );

    $configHeaderArquivo = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 9,
        "5" => 1,
        "6" => 14,
        "7" => 20,
        "8" => 5,
        "9" => 1,
        "10" => 12,
        "11" => 1,
        "12" => 1,
        "13" => 30,
        "14" => 30,
        "15" => 10,
        "16" => 1,
        "17" => 8,
        "18" => 6,
        "19" => 6,
        "20" => 3,
        "21" => 5,
        "22" => 20,
        "23" => 20,
        "24" => 29,
    );

    $configTypeHeaderArquivo = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "str",
        "5" => "num",
        "6" => "num",
        "7" => "str",
        "8" => "num",
        "9" => "str",
        "10" => "num",
        "11" => "str",
        "12" => "str",
        "13" => "str",
        "14" => "str",
        "15" => "str",
        "16" => "num",
        "17" => "num",
        "18" => "num",
        "19" => "num",
        "20" => "num",
        "21" => "num",
        "22" => "str",
        "23" => "str",
        "24" => "str",
    );

    $headerLote = array(
        // CONTROLE
        'banco'          => '756', // Código do Sicoob na Compensação: "756"
        'lote'           => '0001', // "Lote de Serviço: Número seqüencial para identificar univocamente um lote de serviço. Criado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo. Preencher com '0001' para o primeiro lote do arquivo. Para os demais: número do lote anterior acrescido de 1. O número não poderá ser repetido dentro do arquivo."
        'registro'       => '1', // Tipo de Registro: "1"

        // SERVIÇO
        'operacao'       => 'R', // Tipo de Operação: "R"
        'servico'        => '01', // Tipo de Serviço: "01"
        'CNAB_1'         => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
        'layout_lote'    => '040', // Nº da Versão do Layout do Lote: "040"

        // CNAB
        'CNAB_2'         => '', // Uso Exclusivo FEBRABAN / CNAB: Brancos

        // EMPRESA
        'tipo_inscricao' => '2' , // Tipo de Inscrição da Empresa: '1'  =  CPF '2'  =  CGC / CNPJ
        'num_inscricao'  => '19082178000157', //Número de Inscrição da Empresa
        'convenio'       => '', // Código do Convênio no Sicoob: Brancos
        'agencia'        => '41033', // Prefixo da Cooperativa (5 digitos)
        'agencia_dv'     => '3', // Dígito Verificador do Prefixo (1 digito)
        'conta'          => '36838', // Conta Corrente
        'conta_dv'       => '8', // Dígito Verificador da Conta
        'dv'             => '', // Dígito Verificador da Ag/Conta: Brancos
        'nome_empresa'   => 'FUNERARIA RENASCER DIAMANTINA', // Nome da Empresa

        // INFORMAÇÕES
        'informacao_1'   => '', // Mensagem 1: Texto referente a mensagens que serão impressas em todos os boletos referentes ao mesmo lote. Estes campos não serão utilizados no arquivo retorno.
        'informacao_2'   => '', // Mensagem 2: Texto referente a mensagens que serão impressas em todos os boletos referentes ao mesmo lote. Estes campos não serão utilizados no arquivo retorno.

        // CONTROLE DA COBRANÇA
        'num_remessa'    => '00000001', // Número Remessa/Retorno: Número adotado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo para identificar a seqüência de envio ou devolução do arquivo entre o Beneficiário e o Sicoob.
        'dt_gravacao'    => $data->format('dmY'), // Data de Gravação Remessa/Retorno
        'dt_credito'     => '', // Data do Crédito: "00000000"

        //CNAB
        'CNAB_3'         => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
    );

    $configHeaderLote = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 1,
        "5" => 2,
        "6" => 2,
        "7" => 3,
        "8" => 1,
        "9" => 1,
        "10" => 15,
        "11" => 20,
        "12" => 5,
        "13" => 1,
        "14" => 12,
        "15" => 1,
        "16" => 1,
        "17" => 30,
        "18" => 40,
        "19" => 40,
        "20" => 8,
        "21" => 8,
        "22" => 8,
        "23" => 33,
    );

    $configTypeHeaderLote = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "str",
        "5" => "num",
        "6" => "str",
        "7" => "num",
        "8" => "str",
        "9" => "num",
        "10" => "num",
        "11" => "str",
        "12" => "num",
        "13" => "str",
        "14" => "num",
        "15" => "str",
        "16" => "str",
        "17" => "str",
        "18" => "str",
        "19" => "str",
        "20" => "num",
        "21" => "num",
        "22" => "num",
        "23" => "str",
    );

    $detalheSegmentoP = array(
        // CONTROLE
        'banco'             => '756', // Código do Sicoob na Compensação: "756"
        'lote'              => '00001', // Lote de Serviço: Número seqüencial para identificar univocamente um lote de serviço. Criado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo. Preencher com '0001' para o primeiro lote do arquivo. Para os demais: número do lote anterior acrescido de 1. O número não poderá ser repetido dentro do arquivo.
        'registro'          => '3', // Tipo de Registro: "3"
        'num_registro'      => '00001', // Nº Sequencial do Registro no Lote: Número adotado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo, para identificar a seqüência de registros encaminhados no lote. Deve ser inicializado sempre em '1', em cada novo lote.
        'segmento'          => 'P', //Cód. Segmento do Registro Detalhe: "P"
        // CNAB
        'CNAB_1'            => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
        // MOVIMENTO
        'cod_movimento'     => '01', // Código de Movimento Remessa: '01' = Entrada de Títulos
        // DADOS BANCARIOS CLIENTE
        'agencia'           => '41033', // Prefixo da Cooperativa (5 digitos)
        'agencia_dv'        => '3', // Dígito Verificador do Prefixo (1 digito)
        'conta'             => '3683-8', // Conta Corrente
        'conta_dv'          => '8', // Dígito Verificador da Conta
        'dv'                => '', // Dígito Verificador da Ag/Conta: Brancos
        // NOSSO NUMERO
        'nosso_numero'      => '21315649876521216121', // Nosso Número
        // DADOS COBRANÇA
        'carteira'          => '1', // Código da Carteira
        'cadastramento'     => '0', // Forma de Cadastr. do Título no Banco: "0"
        'documento'         => '', // Tipo de Documento: Brancos
        'emissao_boleto'    => '2', // Identificação da Emissão do Boleto: (vide planilha ""Capa"" deste arquivo) '1'  =  Sicoob Emite '2'  =  Beneficiário Emite
        'dist_boleto'       => '2', // Identificação da Distribuição do Boleto: (vide planilha ""Capa"" deste arquivo) '1'  =  Sicoob Distribui '2'  =  Beneficiário Distribui
        'num_documento'     => '1', // Número do Documento de Cobrança: Número adotado e controlado pelo Cliente, para identificar o título de cobrança. Informação utilizada pelo Sicoob para referenciar a identificação do documento objeto de cobrança. Poderá conter número de duplicata, no caso de cobrança de duplicatas; número da apólice, no caso de cobrança de seguros, etc
        'dt_vencimento'     => '24032016', // Data de Vencimento do Título
        'vlr_titulo'        => '3000', // Valor Nominal do Título
        'ag_cobradora'      => '00000', // Agência Encarregada da Cobrança: "00000"
        'ag_cobradora_dv'   => '', // Dígito Verificador da Agência: Brancos
        'especie_titulo'    => '02', // Espécie do titulo 02: Duplicata Mercantil
        'aceite'            => 'A', // Identific. de Título Aceito/Não Aceito: Código adotado pela FEBRABAN para identificar se o título de cobrança foi aceito (reconhecimento da dívida pelo Pagador). 'A'  =  Aceite 'N'  =  Não Aceite
        'dt_emissao_titulo' => '24022016', // Data da Emissão do Título
        'cod_juros_mora'    => '1', // Código do Juros de Mora: '0'  =  Isento '1'  =  Valor por Dia '2'  =  Taxa Mensal
        'dt_juros_mora'     => '24032016', // Data do Juros de Mora: preencher com a Data de Vencimento do Título
        'juros_mora'        => '', // Juros de Mora por Dia/Taxa ao Mês Valor = R$ ao dia Taxa = % ao mês
        'cod_desconto_1'    => '', // Código do Desconto 1: '0'  =  Não Conceder desconto '1'  =  Valor Fixo Até a Data Informada '2'  =  Percentual Até a Data Informada
        'dt_desconto_1'     => '', // Data do Desconto 1
        'desconto_1'        => '', // Valor/Percentual a ser Concedido
        'vlr_IOF'           => '', // Valor do IOF a ser Recolhido
        'vlr_abatimento'    => '', // Valor do Abatimento
        'uso_empresa'       => '', // Identificação do Título na Empresa: Campo destinado para uso do Beneficiário para identificação do Título.
        'cod_protesto'      => '1', // Código para Protesto: "1"
        'dias_protesto'     => '', // Número de Dias Corridos para Protesto
        'cod_baixa_devol'   => '0', // Código para Baixa/Devolução: "0"
        'prazo_baixa_devol' => '', // Número de Dias para Baixa/Devolução: Brancos
        'cod_moeda'         => '09', // Código da Moeda: '02'  =  Dólar Americano Comercial (Venda) '09'  = Real
        'num_contrato'      => '0000000000', // Nº do Contrato da Operação de Créd.: "0000000000"
        // CNAB
        'CNAB_2'            => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
    );

    $configDetalheSegmentoP = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 5,
        "5" => 1,
        "6" => 1,
        "7" => 2,
        "8" => 5,
        "9" => 1,
        "10" => 12,
        "11" => 1,
        "12" => 1,
        "13" => 20,
        "14" => 1,
        "15" => 1,
        "16" => 1,
        "17" => 1,
        "18" => 1,
        "19" => 15,
        "20" => 8,
        "21" => 13,
        "22" => 5,
        "23" => 1,
        "24" => 2,
        "25" => 1,
        "26" => 8,
        "27" => 1,
        "28" => 8,
        "29" => 13,
        "30" => 1,
        "31" => 8,
        "32" => 13,
        "33" => 13,
        "34" => 13,
        "35" => 25,
        "36" => 1,
        "37" => 2,
        "38" => 1,
        "39" => 3,
        "40" => 2,
        "41" => 10,
        "42" => 1,
    );

    $configTypeDetalheSegmentoP = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "num",
        "5" => "str",
        "6" => "str",
        "7" => "num",
        "8" => "num",
        "9" => "str",
        "10" => "num",
        "11" => "str",
        "12" => "str",
        "13" => "str",
        "14" => "num",
        "15" => "num",
        "16" => "str",
        "17" => "num",
        "18" => "str",
        "19" => "str",
        "20" => "num",
        "21" => "num",
        "22" => "num",
        "23" => "str",
        "24" => "num",
        "25" => "str",
        "26" => "num",
        "27" => "num",
        "28" => "num",
        "29" => "num",
        "30" => "num",
        "31" => "num",
        "32" => "num",
        "33" => "num",
        "34" => "num",
        "35" => "str",
        "36" => "num",
        "37" => "num",
        "38" => "num",
        "39" => "str",
        "40" => "num",
        "41" => "num",
        "42" => "str",
    );

    $detalheSegmentoQ = array(
        // CONTROLE
        'banco'             => '756', // Código do Sicoob na Compensação: "756"
        'lote'              => '0001', // Lote de Serviço: Número seqüencial para identificar univocamente um lote de serviço. Criado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo. Preencher com '0001' para o primeiro lote do arquivo. Para os demais: número do lote anterior acrescido de 1. O número não poderá ser repetido dentro do arquivo.
        'registro'          => '3', // Tipo de Registro: "3"
        // SERVIÇO
        'num_servico'       => '1', // Nº Sequencial do Registro no Lote: Número adotado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo, para identificar a seqüência de registros encaminhados no lote. Deve ser inicializado sempre em '1', em cada novo lote.
        'segmento'          => 'Q', // Cód. Segmento do Registro Detalhe: "Q"
        // CNAB
        'CNAB_1'            => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
        // MOVIMENTO
        'cod_movimento'     => '01', // Código de Movimento Remessa: '01' = Entrada de Títulos
        // DADOS PAGADOR
        'tipo_pagador'      => '1', // "Tipo de Inscrição Pagador: '1'  =  CPF '2'  =  CGC / CNPJ
        'inscricao'         => '11497282640', // Número de Inscrição
        'nome'              => 'PEDRO HENRIQUE FAGUNDES BOTELHO', // Nome pagador
        'endereco'          => 'Rua Luizania', // Endereço pagador
        'bairro'            => 'Cidade Nova', // Bairro pagador
        'cep'               => '39401003', // CEP pagador
        'sufixo_cep'        => '003', // Sufixo do CEP do pagador
        'cidade'            => 'Montes Claros', // Cidade pagador
        'uf'                => 'MG', // Unidade Federativa
        // SACADOR AVALISTA
        'tipo_sacador'      => '', // "Tipo de Inscrição Sacador Avalista: '1'  =  CPF '2'  =  CGC / CNPJ
        'inscricao_sacador' => '', // Número de Inscrição
        'nome_sacador'      => '', // Nome sacador
        // OUTROS
        'cod_banco_comp'    => '001', // Cód. Bco. Corresp. na Compensação: Caso o Beneficiário não tenha contratado a opção de Banco Correspondente com o Sicoob, preencher com ""000""; Caso o Beneficiário tenha contratado a opção de Banco Correspondente com o Sicoob e a emissão seja a cargo do Sicoob (SEQ 17.3.P do Segmento P do Detalhe), preencher com ""001"" (Banco do Brasil)
        'nosso_numero_bco'  => '1323739', // Nosso Nº no Banco Correspondente: ""1323739"" O campo NN deve ser preenchido, somente nos casos em que o campo anterior tenha indicado o uso do Banco Correspondente. Obs.: O preenchimento deste campo será alinha à esquerda a partir da posição 213 indo até 219.
        // CNAB
        'CNAB_2'            => '', //Uso Exclusivo FEBRABAN/CNAB
    );

    $configDetalheSegmentoQ = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 5,
        "5" => 1,
        "6" => 1,
        "7" => 2,
        "8" => 1,
        "9" => 15,
        "10" => 40,
        "11" => 40,
        "12" => 15,
        "13" => 5,
        "14" => 3,
        "15" => 15,
        "16" => 2,
        "17" => 1,
        "18" => 15,
        "19" => 40,
        "20" => 3,
        "21" => 20,
        "22" => 8,
    );

    $configTypeDetalheSegmentoQ = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "num",
        "5" => "str",
        "6" => "str",
        "7" => "num",
        "8" => "num",
        "9" => "num",
        "10" => "str",
        "11" => "str",
        "12" => "str",
        "13" => "num",
        "14" => "num",
        "15" => "str",
        "16" => "str",
        "17" => "num",
        "18" => "num",
        "19" => "str",
        "20" => "num",
        "21" => "str",
        "22" => "str",
    );

    $trailerLote = array(
        // CONTROLE
        'banco'                         => '756', // Código do Sicoob na Compensação: "756"
        'lote'                          => '0001', // Lote de Serviço: Número seqüencial para identificar univocamente um lote de serviço. Criado e controlado pelo responsável pela geração magnética dos dados contidos no arquivo. Preencher com '0001' para o primeiro lote do arquivo. Para os demais: número do lote anterior acrescido de 1. O número não poderá ser repetido dentro do arquivo.
        'registro'                      => '5', // Tipo de Registro: "5"
        // CNAB
        'CNAB_1'                        => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
        // DADOS DOS REGISTROS
        'qtd_registros'                 => '1', // Quantidade de Registros no Lote
        'total_cobranca_simples'        => '3000', // Quantidade de Títulos em Cobrança Simples
        'vlr_total_cobranca_simples'    => '', // Valor Total dos Títulos em Carteiras
        'total_cobranca_vinculada'      => '', // Quantidade de Títulos em Cobrança vinculada
        'vlr_total_cobranca_vinculada'  => '', // Valor Total dos Títulos em Carteiras
        'total_cobranca_caucionada'     => '', // Quantidade de Títulos em Cobrança caucionada
        'vlr_total_cobranca_caucionada' => '', // Valor Total dos Títulos em Carteiras
        'total_cobranca_descontada'     => '', // Quantidade de Títulos em Cobrança descontada
        'vlr_total_cobranca_descontada' => '', // Valor Total dos Títulos em Carteiras
        // OUTROS
        'num_aviso'                     => '', // Número do Aviso de Lançamento: Brancos
        // CNAB
        'CNAB_2'                        => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
    );

    $configTrailerLote = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 9,
        "5" => 6,
        "6" => 6,
        "7" => 15,
        "8" => 6,
        "9" => 15,
        "10" => 6,
        "11" => 15,
        "12" => 6,
        "13" => 15,
        "14" => 8,
        "15" => 117,
    );

    $configTypeTrailerLote = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "str",
        "5" => "num",
        "6" => "num",
        "7" => "num",
        "8" => "num",
        "9" => "num",
        "10" => "num",
        "11" => "num",
        "12" => "num",
        "13" => "num",
        "14" => "str",
        "15" => "str",
    );

    $trailerArquivo = array(
        // CONTROLE
        'banco'          => '756', // Código do Sicoob na Compensação: "756"
        'lote'           => '9999', // Preencher com '9999'.
        'registro'       => '9', // Tipo de Registro: "9"
        // CNAB
        'CNAB_1'         => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
        // DADOS DOS REGISTROS
        'qtd_lotes'      => '1', // Quantidade de Lotes do Arquivo
        'qtd_registros'  => '1', // Quantidade de Registros do Arquivo
        'qtd_contas'     => '000001', // Qtde de Contas p/ Conc. (Lotes): "000000"
        // CNAB
        'CNAB_2'         => '', // Uso Exclusivo FEBRABAN/CNAB: Brancos
    );

    $configTrailerArquivo = array (
        "1" => 3,
        "2" => 4,
        "3" => 1,
        "4" => 9,
        "5" => 6,
        "6" => 6,
        "7" => 6,
        "8" => 205,
    );

    $configTypeTrailerArquivo = array (
        "1" => "num",
        "2" => "num",
        "3" => "num",
        "4" => "str",
        "5" => "num",
        "6" => "num",
        "7" => "num",
        "8" => "str",
    );

    montaLinha($headerArquivo, $configHeaderArquivo, $configTypeHeaderArquivo);
    montaLinha($headerLote, $configHeaderLote, $configTypeHeaderArquivo);
    montaLinha($detalheSegmentoP, $configDetalheSegmentoP, $configTypeDetalheSegmentoP);
    montaLinha($detalheSegmentoQ, $configDetalheSegmentoQ, $configTypeDetalheSegmentoQ);
    montaLinha($trailerLote, $configTrailerLote, $configTypeTrailerLote);
    montaLinha($trailerArquivo, $configTrailerArquivo, $configTypeTrailerArquivo);

    function montaLinha($linha, $config, $tipo){
        $novaLinha = '';
        $dadosHeader = array_values($linha);
        $dadosConfig = array_values($config);
        $dadosTipo = array_values($tipo);
        // echo "<pre>";
        for ($i = 0; $i < sizeof($linha); $i++) {
            // echo ("<h1>" . $i . "</h1>");
            if ($dadosTipo[$i] == "num") {
                // echo ($i . " era do tamanho " . strlen($dadosHeader[$i]) . " e deve ficar com " . $dadosConfig[$i]);
                while(strlen($dadosHeader[$i]) < $dadosConfig[$i]){
                    $dadosHeader[$i] = '0' . $dadosHeader[$i];
                }
                // echo (". Ficou com " . strlen($dadosHeader[$i]) . " > " . $dadosHeader[$i] . " (" . $dadosTipo[$i] . ")<br>");
            } if ($dadosTipo[$i] == "str") {
                // echo ($i . " era do tamanho " . strlen($dadosHeader[$i]) . " e deve ficar com " . $dadosConfig[$i]);
                while(strlen($dadosHeader[$i]) < $dadosConfig[$i]){
                    $dadosHeader[$i] = $dadosHeader[$i] . " ";
                }
                // echo (". Ficou com " . strlen($dadosHeader[$i]) . " > " . $dadosHeader[$i] . " (" . $dadosTipo[$i] . ")<br>");
            };
            $novaLinha = $novaLinha . $dadosHeader[$i];
        }
        echo "<pre>";
        print_r($novaLinha);

        // Abre ou cria o arquivo bloco1.txt
        // "a" representa que o arquivo é aberto para ser escrito
        $fp = fopen("remessa.rem", "a");

        // Escreve "exemplo de escrita" no bloco1.txt
        $escreve = fwrite($fp, $novaLinha . "\r\n");

        // Fecha o arquivo
        fclose($fp);
    }


    ///////////////////////////////////
    ///////////////////////////////////
    //                               //
    /*      FUNÇÕES AUXILIARES       */
    //                               //
    ///////////////////////////////////
    ///////////////////////////////////
    function tiraMoeda($valor){
        $pontos = array(",", ".");
        $result = str_replace($pontos, "", $valor);
        return $result;
    }
?>`

**Comment by Rctnet** [comment]
Boa noite , criei um projeto novo e o primeiro layout que disponibilizo é o cnab240 SIGCB caixa, caso queira dar uma olhada entre no meu perfil e encontrara meu projeto, se tiver alguma duvida pode contar comigo

**Comment by criacaosites** [comment]
Como voces enviam a remessa ao sicoob? Ha alguma maneira de se fazer isso automaticamente?
