### ISSUE TITLE
Arquivo de retorno

### ISSUE THREAD

**Issue by wrettich** [andersondanilo/CnabPHP#33]
Fala Anderson,

Estou tentando processar um arquivo de retorno do Itau (400) e ele só me retorna isso:
{
last_error: false,
_codigo_banco: 341
}

Não dá erro em nenhuma linha, estou tentando ver aonde que ele não consegue processar o resto do arquivo. Se souber como corrigir, manda aí por favor.

Obrigado pelo projeto, é bem maneiro!!

Abraços

**Comment by andersondanilo** [comment]
Estranho, você pode usar como exemplo o código do teste unitário:

https://github.com/andersondanilo/CnabPHP/blob/master/tests/Cnab/Retorno/Cnab400/ArquivoTest.php

Para saber se o problema está no CnabPHP você pode tentar ler o arquivo neste site (que usa o CnabPHP).

http://cnab-online.github.io/

**Comment by wrettich** [comment]
Fala Anderson, 

Obrigado pelo retorno, por algum motivo eu fiz besteira e continuei com ela até ver que estava fazendo.
Muito obrigado pelo retorno e agora, por esse link!!!

Grande abraços
