### ISSUE TITLE
Remessa Banco do Brasil

### ISSUE THREAD

**Issue by gabrielrodrigodesbesell** [andersondanilo/CnabPHP#35]
Olá, estou utilizando o projeto para gerar a remessa para a CEF, porém agora preciso gerar para o Banco do Brasil, alguém já implementou? Algum encaminhamento? Obrigado

**Comment by Suhdo** [comment]
Gabriel, vc pode postar o código que gera a remessa para CEF? 
Estou tendo muitos problemas pra gerar em cnab240, desde já obrigado.

**Comment by gabrielrodrigodesbesell** [comment]
Suhdo eu apenas usei a classe do Anderson, funcionou. Você está tendo problemas? Precisa de ajuda?

**Comment by Suhdo** [comment]
Eu também  estou usando a classe do Anderson, porém comigo ela gera erro no momento do ->getText() e não salva o arquivo. Onde será que estou errando, já revirei essa classe do avesso e não consegui. 
Eu usei a classe para o banco itau cnab400 e deu certo, aí peguei ela e alterei para cef e cnab240, pra caixa e não funcionou. Uma ajuda seria de grande valia e eu ficaria muito agradecido.

Desde já obrigado.

**Comment by lucasbsilva** [comment]
Também preciso gerar arquivos de remessa para o Banco do Brasil, o projeto tem suporte à isso?

**Comment by gabrielrodrigodesbesell** [comment]
Suhdo, vc tem permissões de gravação setadas para a pasta de saída do arquivo?

**Comment by Suhdo** [comment]
@gabrielrodrigodesbesell Sim, chmod 777. Para o banco itaú vai tranquilamente.
Pelo que entendi, preciso fazer calculo do digito verificador do código do cedente e do código do cedente mais agência. Acredito que pode ser isso que gera o erro, pois eu estava colocando apenas o digito do código passado pelo banco. Estou correto?

Todavia um exemplo de configuração dessa classe pra caixa poderia me ajudar a comparar os dados.

**Comment by Suhdo** [comment]
Resolvi meu problema pra gerar em cnab240 para cef sigcb.
O que eu estava procurando era isso aqui, um modelo de aplicação para ver os campos exigidos. 
Segue o link para quem teve dificuldades
https://github.com/andersondanilo/CnabPHP/blob/master/tests/Cnab/Remessa/Cnab240/ArquivoTest.php

**Comment by gabrielrodrigodesbesell** [comment]
que bom @Suhdo.

**Comment by andersondanilo** [comment]
Olá @gabrielrodrigodesbesell e @lucasbsilva,

Vocês ainda precisam da remessa para o banco do brasil? qual formato: 240 ou 400? vocês tem alguma documentação?

**Comment by gabrielrodrigodesbesell** [comment]
@andersondanilo, o banco me passou os seguintes documentos:
- http://www.bb.com.br/docs/pub/emp/empl/dwn/CbrVer04BB.pdf
- http://www.febraban.org.br/7Rof7SWg6qmyvwJcFwF7I0aSDf9jyV/sitefebraban/subcpadr12-layout%20padrao%20V%2008%2007%20-%2021.09%20-%20V1.pdf

Veja se ajuda.

**Comment by lucasbsilva** [comment]
Olá @andersondanilo, sim!

Me passaram apenas que preciso da remessa no formato 240.

**Comment by andersondanilo** [comment]
Disponibilizei uma nova versão com a remessa do banco do brasil disponível para testes.

https://github.com/andersondanilo/CnabPHP/blob/master/tests/Cnab/Remessa/Cnab240/BancoDoBrasilTest.php

**Comment by warlleyzulu** [comment]
Bom dia, estou tentando usar o projeto do Anderson para geração de remessas do banco Itaú gostaria de saber se tem alguém que já utilizou e se pode me ajudar a monta a estrutura para eu fazer funcionar.

Desde já agradeço.
