### ISSUE TITLE
Remessa Bradesco

### ISSUE THREAD

**Issue by marcosformagini** [andersondanilo/CnabPHP#36]
Olá, gostei muito do seu projeto, porém sinto a necessidade de ter a geração do arquivo de remessa para o banco do Bradesco. Alguém tem isso implementado ou possui algum material que possa me ajudar?

**Comment by gabrielrodrigodesbesell** [comment]
Marcos, veja o projeto do Thiago: https://github.com/thiagohenrique0810/GARB-Gerador-de-Arquivos-de-Remessa-Bradesco
Verifique se isso lhe ajuda, caso implemente na classe do Anderson por favor compartilhe.

**Comment by Fabyo** [comment]
Boa Tarde
algum teria o manual do cnab do bradesco 400 e 240 ?
obrigado

**Comment by gabrielrodrigodesbesell** [comment]
@Fabyo 
**400:** http://www.bradesco.com.br/portal/PDF/pessoajuridica/solucoes-integradas/outros/layout-de-arquivo/cobranca/4008-524-0121-08-layout-cobranca-versao-portuguesSS28785.pdf

**240:** http://www.bradesco.com.br/portal/PDF/pessoajuridica/solucoes-integradas/outros/layout-de-arquivo/cobranca/4008-524-0339-02-mp-operacionais-troca-arquivos-240-posicoes.pdf

Tem esse projeto do @thiagohenrique0810 que eu acho que pode te ajudar: https://github.com/thiagohenrique0810/GARB-Gerador-de-Arquivos-de-Remessa-Bradesco

**Comment by thiagohenrique0810** [comment]
ola pessoal, minha biblioteca esta funcionando normalmente, porem pretendo fazer algo melhor, pois existem varias coisas que procuro e não acho, como emissão de boletos em massa, envio por email em formato de PDF, criação de carners e outros.

**Comment by Fabyo** [comment]
Oi Thiago qual sua duvida?, o que voce nao achou?, eu desenvolvi um sistema que gera remessa em massa, pdf tbm e manda tudo por email

**Comment by thiagohenrique0810** [comment]
que projeto é esse? vc tem ele no github?

**Comment by Fabyo** [comment]
Nao tenho, pois ainda estou desenvolvendo ele, estou usando o cnab do danilo e criando os outros banco que o do danilo nao da suporte

**Comment by thiagohenrique0810** [comment]
estou pra fazer a mesma coisa Fabyo kkkkkk

**Comment by Fabyo** [comment]
Estou tentando fazer algo completo e depois disponibilizar, se quiser podemos juntar nossas ideias e fazer algo junto

**Comment by thiagohenrique0810** [comment]
blz, minha ideia tambem é fazer algo completo, pois eu possuo um sistema de emissão de boletos e é complicado de mais achar essas coisas

**Comment by Fabyo** [comment]
eu estou desenvolvendo um ERP completo com emissao de nota fiscal eletronica e boletos danfe etc

**Comment by thiagohenrique0810** [comment]
cara tenho uma ideia melhor de ERP uma coisa que os outros não tem

**Comment by thiagohenrique0810** [comment]
me chama no skype: thiagohenrique0810

**Comment by Fabyo** [comment]
mas sobre a ERP é para um cliente tenho que fazer de qualquer forma :)

**Comment by glauberm** [comment]
@thiagohenrique0810 @Fabyo @marcosformagini estou desenvolvendo a questão da remessa do Bradesco em cima do projeto do @andersondanilo. Chequem o último commit desses fork: https://github.com/glauberm/cnab_yaml e https://github.com/glauberm/CnabPHP

**Comment by khlJunior** [comment]
Bom dia Pessoal!
Alguém tem uma solução para este caso ?

@glauberm Eu não consegui encontrar os seus forks. 

Vou começar a brincar com o GARB citado acima mas ficaria muito feliz de manter o CnabPHP no meu projeto.

Abraços

**Comment by rlij** [comment]
Pessoal.. Tenho uma'duvida...
No layout do bradesco para remessa é necessario um incremento de 1 em 1 no header do arquivo... como vocês estao fazendo com isso?

**Comment by winston2016** [comment]
Galera estou precisando de uma ajuda, para configurar o arquivo de remessa do Bradesco.
usei essas configurações iniciais:

$codigo_bancoBradesco = Cnab\Banco::BRADESCO;
$arquivoBradesco = new Cnab\Remessa\Cnab400\Arquivo($codigo_bancoBradesco);
$arquivo->configure(array(
'data_geracao' => new DateTime(),
'data_gravacao' => new DateTime(), 
'nome_fantasia' => 'Nome Fantasia da sua empresa', // seu nome de empresa
'razao_social' => 'Razão social da sua empresa', // sua razão social
'cnpj' => '111', // seu cnpj completo
'banco' => $codigo_bancoBradesco , //código do banco
'logradouro' => 'Logradouro da Sua empresa',
'numero' => 'Número do endereço',
'bairro' => 'Bairro da sua empresa', 
'cidade' => 'Cidade da sua empresa',
'uf' => 'Sigla da cidade, ex SP',
'cep' => 'CEP do endereço da sua cidade',
'agencia' => '1111', 
'conta' => '22222', // número da conta
'conta_dac' => '2', // digito da conta

'codigo_cedente'=> $codigo_bancoBradesco, //está certo é o codigo do banco???
'sequencial_remessa'=>'1', //NAO SEI O QUE É ESSA sequencial_remessa'

));
Porém está dando o seguinte erro:Fatal error: Uncaught exception 'InvalidArgumentException' with message 'field 'codigo_cedente' dont exists' in C:\wamp\www\CnabPHP-master-remessa\src\Cnab\Format\Linha.php on line 15

preciso de uma help;

**Comment by thiagohenrique0810** [comment]
winston, esse é o codigo sequencial que cada remessa possui, é um numero unico, você deve entrar em contato com o banco para saber em qual sequencial você deve começar a gerar, pois cada remessa tem seu codigo sequencial

**Comment by thiagohenrique0810** [comment]
Exemplo utilizando minha biblioteca:
`$boletos_remessa[$i]->sacado_zipcode = str_replace('-', '', $boletos_remessa[$i]->sacado_zipcode);
				
				$boleto['agencia'] 						= $info_conta[0]->agency_code;
				$boleto['agencia_dv'] 					= $info_conta[0]->agency_dv;
				$boleto['razao_conta_corrente']			= '0000';
				$boleto['nosso_numero'] 				= $boletos_remessa[$i]->nosso_numero;
				$boleto['conta'] 						= $info_conta[0]->account_code;
				$boleto['conta_dv'] 					= $info_conta[0]->accont_dv;
				$boleto['carteira'] 					= $boletos_remessa[$i]->wallet;
				$boleto['habilitar_multa'] 				= true;
				$boleto['percentual_multa'] 			= '0';
				
				$boleto['desconto_dia']	 				= '0';
				$boleto['rateio'] 						= false;
				$boleto['numero_documento'] 			= $boletos_remessa[$i]->numero_documento;
				$boleto['vencimento'] 					= date('dmy', strtotime($boletos_remessa[$i]->vencimento));
				$boleto['valor'] 						= number_format($boletos_remessa[$i]->valor_boleto,2,"","");
				$boleto['data_emissao_titulo'] 			= date('dmy', $boletos_remessa[$i]->data_processamento);
				$boleto['valor_dia_atraso'] 			= '0';
				$boleto['data_limite_desconto'] 		= date('dmy', $boletos_remessa[$i]->vencimento);
				$boleto['valor_desconto'] 				= '0';
				$boleto['valor_iof'] 					= '0';
				$boleto['valor_abatimento_concedido'] 	= '0';
				$boleto['tipo_inscricao_pagador'] 		= 'CPF';
				$boleto['numero_inscricao'] 			= $this->limpaCPF_CNPJ($boletos_remessa[$i]->sacado_cpf);
				$boleto['nome_pagador'] 				= utf8_decode($this->criaResumo($boletos_remessa[$i]->sacado_name, 36));
				$boleto['endereco_pagador'] 			= utf8_decode($this->criaResumo($boletos_remessa[$i]->sacado_address, 36));
				$boleto['primeira_mensagem'] 			= '';
				$boleto['cep_pagador'] 					= substr($boletos_remessa[$i]->sacado_zipcode, 0, 5);
				$boleto['sufixo_cep_pagador'] 			= substr($boletos_remessa[$i]->sacado_zipcode, 5, 7);
				$boleto['sacador_segunda_mensagem'] 	= '';
				
				$boletos[] = $boleto;
				$arquivo_remessa->add_boleto($boleto);`

**Comment by winston2016** [comment]
não entendi, vou entrar em contato com o banco para verificar esse número;. 
Mas esse código sequencial é da variavel sequencial_remessa,
e sobre o codigo_cedente.

**Comment by thiagohenrique0810** [comment]
para o codigo do cedente é o mesmo procedimento para identifica-lo, vc deve entrar em contato com o bradesco netempresas para solicita-lo, quando gerar o arquivo de remessa vc deve envia-lo com a estensão .RTS para que seja interpretado como arquivo de testes
o retorno desse envio por parte do banco é gerado em ate 24 horas

**Comment by derlanoliver** [comment]
winston2016 estou com o mesmo problema.. você conseguiu resolver?
Ele não reconhece e nem aparece no arquivo de remessa o código do Cedente.
obs.: O banco já me passou o código do cedente.

**Comment by jordankobellarz** [comment]
@derlanoliver e @winston2016  estou com o mesmo problema. Adicionei o campo 'codigo_cedente' no YAML de remessa, como sugere [esse arquivo](https://github.com/andersondanilo/cnab_yaml/blob/master/cnab400/237/remessa/header_arquivo.yml), e mesmo assim está dando o erro: **Fatal error: Uncaught exception 'InvalidArgumentException' with message 'field 'codigo_cedente' dont exists' in (...) Cnab/Format/Linha.php:15.**

Se eu remover o 'codigo_cedente' do array passado como parâmetro do método `configure` da classe `Cnab\Remessa\Cnab400\Arquivo`, daí dá o erro **Uncaught exception 'Exception' with message 'Configuração "codigo_cedente" need to be set' in (...) Cnab/Remessa/Cnab400/Arquivo.php:54**

Vocês conseguiram implementar a geração do arquivo de remessa para o Bradesco de 400 posições?

**Comment by winston2016** [comment]
Bom dia Amigo.
Para poder te ajudar. eu usei o GARB-Gerador-de-Arquivos-de-Remessa-Bradesco do thiagohenrique0810,
Está funcionando perfeitamente.

**Comment by jordankobellarz** [comment]
@winston2016 testei aqui o [GARB](https://github.com/thiagohenrique0810/GARB-Gerador-de-Arquivos-de-Remessa-Bradesco) e aparentemente está funcionando. Só preciso homologar com o banco. Obrigado!

**Comment by winston2016** [comment]
@jordankobellarz  Magina. Agradeça o @andersondanilo  e o  @thiagohenrique0810 . rs

**Comment by thiagohenrique0810** [comment]
galera criei uma lib para integração da API de envio automatico de remessas do banco itau 👍 
https://github.com/thiagohenrique0810/Atari

**Comment by Aneitzke** [comment]
Pessoal, o projeto contempla com o envio de remessa e retorno para quais bancos?
Esta bem completo?
