### ISSUE TITLE
Duvida processamento de Remessa Itaú [teste]

### ISSUE THREAD

**Issue by loja5combr** [andersondanilo/CnabPHP#37]
Ola a todos, gostaria de tira uma duvida de alguém que já usa o sistema para envio de remessas para o Itaú, gerei uma remessa com alguns boletos de teste e envie no sistema do Itaú no modo de teste, após o processamento o foi informado que ocorreu um erro descrito abaixo, pelo que atendi algo relacionado a agencia/conta, mas as mesmas estão corretas e já uso para receber boleto (sem registro atualmente), alguém já teve este problema? Fiz testes usando a carteira 109.

Arquivo de COBRANCA - 400 - 02031618.REM      Enviado em - 01/03/2016  
Agência/Conta:	884X-1589Y
Quantidade de Registro(s):	4
**AG/CTA S/ CAD.INTERCAMBIO/NÃO PERTENCE AO GRUPO CO** Conteúdo: 884X001589Y
(*) Favor checar arquivo retorno no próximo dia útil para detalhamento do resultado do processamento.

**Comment by Suhdo** [comment]
Se vc for no site do banco, e la em "Transmissão de Arquivos" depois em "Envio de Remessa" e não estiver habilitado o cobrança 400.. vc precisa ir até o gerente da conta e pedir pra instalar o produto "INTERCAMBIO DE ARQUIVOS" configurado para o serviço "Cobrança 400". Torço pra que o seu gerente não seja um analfabeto digital igual ao meu. 

Abraço.

**Comment by loja5combr** [comment]
Ola, sim a mesma já esta ativada.
