### ISSUE TITLE
Sispag itau

### ISSUE THREAD

**Issue by leopucci** [andersondanilo/CnabPHP#38]
Boa tarde pessoal. 
Alguem ja utilizou este projeto para o sispag do itau ao inves de cobrança?
Quando falo sispag estou falando  no sistema de envio de pagamentos. Boletos, transferencias, guias de imposto etc. 
Outra duvida que fiquei tambem é se o sispag eh 400 ou 240 pois na net achei apenas manuais 240
Abraco

**Comment by leopucci** [comment]
É... não tem..
Vou fazer!

**Comment by dlimars** [comment]
@leopucci chegou a desenvolver algo relativo ao sispag do itaú? estou desenvolvendo isso também.

**Comment by leopucci** [comment]
Fala Daniel, cara eu só prototipei ainda, nem comecei a criar as funções.
tá aqui oh: https://github.com/leopucci/cnab_yaml/commits/master

Só dei uma traduzida do pdf pra yaml, nem terminei todos porque tem outros projetos pegando aqui. 
mas já pega os yml que ja gerei pra nao precisar ficar pegando do pdf de novo!

**Comment by juanmonstra** [comment]
Opa Pessoal, estou fazendo a implementação desse modelo. Como posso fazer para contribuir aqui com vocês?
Abraços

**Comment by leopucci** [comment]
Oi Juan, dá uma olhada nos 2 commits que eu fiz aqui por ultimo ó.:
https://github.com/leopucci/cnab_yaml/commits/master

Eu já modelei, baseado no pdf do itaú, praticamente todos os modelos. (
https://github.com/leopucci/cnab_yaml/commit/e99109786fa2acd49fd5159f34d7a80c951da569
)
Aproveite e faça o pull request destes arquivos pro repositório original.
Eu travei minha senha sem o token aqui, e nao consigo reativar entao nao
consigo subir.

O que tem que ser feito agora, é a codificação php, seguindo os moldes do
projeto, utilizando o yaml que eu ja fiz.

Cria uma pasta Cnab240CobrancaItau ou algo neste sentido.
SEgue o modelo dos arquivos da pasta cnab240 (
https://github.com/andersondanilo/CnabPHP/tree/master/src/Cnab/Remessa/Cnab240
)

Lembre-se que existe a pasta na Pasta Remessa (quando é enviado pro banco)
e no retorno (quando volta do banco). Eu nao sei se compensa integrar tudo
na mesma pasta.
Acho que numa primeira etapa seria mais facil pra voce só pensar na
implementaçao primeiro sem ter que ficar pensando em merge.
Entao sugeriria este caminho!

Veja o exemplo de como criar um arquivo de remessa, que acho que pelo menos
a parte da remessa voce já irá entender.
https://github.com/andersondanilo/CnabPHP/wiki/Criando-um-arquivo-de-remessa#criando-um-arquivo-de-remessa

No Caso para esta configuração que te falei, esta linha de carregamento do
arquivo ficaria assim

$arquivo = new Cnab\Remessa\Cnab240CobrancaItau\Arquivo($codigo_banco)


Tendo duvidas sobre quais nomes dar, nao se preocupe muito. Se voce
conseguir contribuir já está otimo. Tenta apenas usar o bom senso e usar
nomes faceis e obvios para ficar claro.

Na hora do pull request alguem ajusta caso tiver um padrao, mas se voce já
contribuir com a codificação está ótimo!

Abraço
Pucci




2017-07-13 22:23 GMT-03:00 juanmonstra <notifications@github.com>:
