### ISSUE TITLE
Formatar código de acordo com as PSRs

### ISSUE THREAD

**Issue by viniciusss** [andersondanilo/CnabPHP#39]
Formatar o código utilizando os padrões das PRS.

**Comment by andersondanilo** [comment]
Aguardamos sua contribuição, Obrigado!

**Comment by viniciusss** [comment]
Tranquilo... pretendo utilizar o http://cs.sensiolabs.org/, algum problema?

2016-03-07 19:33 GMT-03:00 Anderson Danilo <notifications@github.com>:

> Aguardamos sua contribuição, Obrigado!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersondanilo/CnabPHP/issues/39#issuecomment-193486478>
> .
>



-- 
------------------------------
Vinicius de Sá
Desenvolvimento de Sistemas - Móveis de Simonetti
Zend Certified PHP Engineer <http://www.zend.com/en/yellow-pages/ZEND016042>
(27) 99986-4288 - (27) 3765-0880

**Comment by andersondanilo** [comment]
Agradeço a sua contribuição
