### ISSUE TITLE
Erro no código da espécie para Caixa Econômica Federal

### ISSUE THREAD

**Issue by raphox** [andersondanilo/CnabPHP#41]
No código atual do branch master está:

```php
// https://github.com/andersondanilo/CnabPHP/blob/master/src/Cnab/Especie.php#L22
const CEF_DUPLICATA_MERCANTIL = '01';
```

Acredito que essa informação está errada.

Mas no arquivo de layout da Caixa (http://www.caixa.gov.br/Downloads/cobranca-caixa-manuais/Manual_Leiaute_CNAB240_SIGCB.pdf) os valores reais são:

```
01 CH Cheque
02 DM Duplicata Mercantil
03 DMI Duplicata Mercantil p/ Indicação
04 DS Duplicata de Serviço
05 DSI Duplicata de Serviço p/ Indicação
06 DR Duplicata Rural
07 LC Letra de Câmbio
08 NCC Nota de Crédito Comercial
09 NCE Nota de Crédito a Exportação
10 NCI Nota de Crédito Industrial
11 NCR Nota de Crédito Rural
12 NP Nota Promissória
13 NPR Nota Promissória Rural
14 TM Triplicata Mercantil
15 TS Triplicata de Serviço
16 NS Nota de Seguro
17 RC Recibo
18 FAT Fatura
19 ND Nota de Débito
20 AP Apólice de Seguro
21 ME Mensalidade Escolar
22 PC Parcela de Consórcio
23 NF Nota Fiscal
```

**Comment by andersondanilo** [comment]
Está sim, antes da remessa CNAB240 ser desenvolvida o objetivo era desenvolver a CNAB400, por isso houve este conflito de informações (http://afsys.info/download/cobcaixa_layout_400.pdf).

https://github.com/andersondanilo/CnabPHP/commit/ef179d0fa2e8cb50a843c6b98392cb5127f75b00
