### ISSUE TITLE
Header de Arquivo CEF CNAB240

### ISSUE THREAD

**Issue by FrankBruno** [andersondanilo/CnabPHP#42]
Caro Anderson, ao realizar criação da remessa para CEF, modelo CNAB 240, o Header do arquivo está dando uma diferença.

Conteúdo enviado:

object(Cnab\Remessa\Cnab240\Arquivo)[255]
  public 'headerArquivo' => null
  public 'headerLote' => null
  public 'detalhes' => 
    array (size=0)
      empty
  public 'trailerLote' => null
  public 'trailerArquivo' => null
  private '_data_gravacao' => null
  private '_data_geracao' => null
  public 'banco' => 
    array (size=2)
      'codigo_do_banco' => int 104
      'nome_do_banco' => string 'C ECON FEDERAL' (length=14)
  public 'codigo_banco' => string '104' (length=3)
  public 'configuracao' => 
    array (size=0)
      empty
  public 'layoutVersao' => string 'sigcb' (length=5)

Array do Header
array (size=18)
  'numero_sequencial_arquivo' => int 555
  'operacao' => string 'R' (length=1)
  'banco' => string '104' (length=3)
  'agencia' => string '3366' (length=4)
  'agencia_dv' => string '9' (length=1)
  'conta' => int 77
  'data_geracao' => 
    object(DateTime)[5673]
      public 'date' => string '2016-03-11 18:09:29.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'UTC' (length=3)
  'data_gravacao' => 
    object(DateTime)[5688]
      public 'date' => string '2016-03-11 18:09:29.000000' (length=26)
      public 'timezone_type' => int 3
      public 'timezone' => string 'UTC' (length=3)
  'codigo_cedente' => int 443459
  'nome_fantasia' => string ' LOJAS SIMONETTI LTDA' (length=21)
  'razao_social' => string ' LOJAS SIMONETTI LTDA' (length=21)
  'cnpj' => string '31.743.818/0001-28' (length=18)
  'logradouro' => string 'RUA CARLOS CASTRO' (length=17)
  'numero' => string '245' (length=3)
  'bairro' => string 'CENTRO' (length=6)
  'cidade' => string 'PINHEIROS' (length=9)
  'uf' => string 'ES' (length=2)
  'cep' => int 29980000

A crítica está no Uso Exclusivo Uso Exclusivo CAIXA 
Inicio: 33 Fim: 52  Tamanho: 20

Conteúdo Atual:03366000000000778000
Conteúdo Esperado:0000000000000000000

O que devo fazer para chegar ao conteúdo esperado?

Obrigado.

**Comment by andersondanilo** [comment]
Corrigido na versão 1.3.15
Commit: https://github.com/andersondanilo/CnabPHP/commit/5bb74ff91ecc368da1f30baba592b7179698a2c9
