### ISSUE TITLE
Problemas leitura do arquivo Santander

### ISSUE THREAD

**Issue by thaiscirqueira** [andersondanilo/CnabPHP#43]
Anderson, tudo bem?

Estou com problemas na leitura do arquivo do Santander.
Na class Arquivo.php quando ele verifica o $lote->listDetalhes() o mesmovem vazio.
O que pode ser?

**Comment by andersondanilo** [comment]
Pode ser o formato do arquivo, tente abrir ele neste site: http://cnab-online.github.io/ (que usa o CnabPHP).

Se você não conseguir me envie o  arquivo.

**Comment by thaiscirqueira** [comment]
Anderson,
Esse é o arquivo.

Em 13 de março de 2016 14:35, Anderson Danilo <notifications@github.com>
escreveu:

> Pode ser o formato do arquivo, tente abrir ele neste site:
> http://cnab-online.github.io/ (que usa o CnabPHP).
>
> Se você não conseguir me envie o arquivo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andersondanilo/CnabPHP/issues/43#issuecomment-196009658>
> .
>



-- 
--
Thais Cirqueira
email: thaiscirqueira@gmail.com
Celular: 11 - 9 8281 5784
skype: thaiscirqueira

03300000         2168093510001880033434700490138867304347 0000130014674 EASY TAXI SERVICOS SA         SANTANDER                               21003201616154400185706000000                                                                     
03300011C2003031 2168093510001880033434700490138867304347 0000130014674 EASY TAXI SERVICOS SA                                                                               00000                                   00000000                    
0330001300001A3337000410083100003585293808 LUIZ CARLOS MEDINA            1004035000100191    09032016BRL0000000000000000000000000016501004035000100191    09032016000000000001650                                        01          0ZAZ6      
0330001300002B   100017855136053                              00000                                                  00000000  090320160000000000016500000000000000000000000000000000000000000000000000000000000000000                          
0330001300003A3337000010703400000000059803 JOSE LOURENCO DA SILVA        1004035000100265    09032016BRL0000000000000000000000000016281004035000100265    09032016000000000001628                                        01          0ZAZ6      
0330001300004B   100085244457853                              00000                                                  00000000  090320160000000000016280000000000000000000000000000000000000000000000000000000000000000                          
0330001300005A3337001040066400013007255694 JOSUE DE SOUSA ANSELMO JUNIOR 1004035000100669    09032016BRL0000000000000000000000000015371004035000100669    09032016000000000001537                                        01          0ZAZ6      
0330001300006B   100000160185165                              00000                                                  00000000  090320160000000000015370000000000000000000000000000000000000000000000000000000000000000                          
0330001300007A3337001040155100013007217880 RONY DE OLIVEIRA E SILVA      1004035000100945    09032016BRL0000000000000000000000000014861004035000100945    09032016000000000001486                                        01          0ZAZ6      
0330001300008B   100099768674172                              00000                                                  00000000  090320160000000000014860000000000000000000000000000000000000000000000000000000000000000                          
0330001300009A3337001040081000013000048386 CARLOS LINCOLN DE SOUZA FEITOS1004035000101267    09032016BRL0000000000000000000000000014021004035000101267    09032016000000000001402                                        01          0ZAZ6      
0330001300010B   100074064371453                              00000                                                  00000000  090320160000000000014020000000000000000000000000000000000000000000000000000000000000000                          
0330001300011A3337000010350400000000294527 ROGERIO MARTINS FERREIRA      1004035000101621    09032016BRL0000000000000000000000000013201004035000101621    09032016000000000001320                                        01          0ZAZ6      
0330001300012B   100006746457400                              00000                                                  00000000  090320160000000000013200000000000000000000000000000000000000000000000000000000000000000                          
0330001300013A3337003410326100000000011286 MARCELO RODRIGUES DOS SANTOS  1004035000101667    09032016BRL0000000000000000000000000013201004035000101667    09032016000000000001320                                        01          0ZAZ6      
0330001300014B   100001608123723                              00000                                                  00000000  090320160000000000013200000000000000000000000000000000000000000000000000000000000000000                          
0330001300015A3337000010345800000000189995 JOSENILTON SANTANA DE JESUS   1004035000101767    09032016BRL0000000000000000000000000013031004035000101767    09032016000000000001303                                        01          0ZAZ6      
0330001300016B   100092326617568                              00000                                                  00000000  090320160000000000013030000000000000000000000000000000000000000000000000000000000000000                          
0330001300017A3337001040102800013000280140 NADELMO GENARIO DA SILVA      1004035000102157    09032016BRL0000000000000000000000000012131004035000102157    09032016000000000001213                                        01          0ZAZ6      
0330001300018B   100002663618462                              00000                                                  00000000  090320160000000000012130000000000000000000000000000000000000000000000000000000000000000                          
0330001300019A3337000010353700000000148075 DAVI SILVA DA ROCHA           1004035000102229    09032016BRL0000000000000000000000000011931004035000102229    09032016000000000001193                                        01          0ZAZ6      
0330001300020B   100065614550020                              00000                                                  00000000  090320160000000000011930000000000000000000000000000000000000000000000000000000000000000                          
0330001300021A3337001040045200013000617989 JORGE LUIS TRINDADE LOBATO    1004035000102257    09032016BRL0000000000000000000000000011881004035000102257    09032016000000000001188                                        01          0ZAZ6      
0330001300022B   100038170191068                              00000                                                  00000000  090320160000000000011880000000000000000000000000000000000000000000000000000000000000000                          
0330001300023A3337000010352900000000738883 PAULO SERGIO PIUGA ALVES      1004035000102419    09032016BRL0000000000000000000000000011441004035000102419    09032016000000000001144                                        01          0ZAZ6      
0330001300024B   100054500192034                              00000                                                  00000000  090320160000000000011440000000000000000000000000000000000000000000000000000000000000000                          
0330001300025A3337003410508200000000028100 JOSE MARIA SEVERO DA SILVA    1004035000102641    09032016BRL0000000000000000000000000011001004035000102641    09032016000000000001100                                        01          0ZAZ6      
0330001300026B   100060905557034                              00000                                                  00000000  090320160000000000011000000000000000000000000000000000000000000000000000000000000000000                          
0330001300027A3337001040174600001000130548 PAULO FERNANDO DE OLIVEIRA    1004035000102643    09032016BRL0000000000000000000000000011001004035000102643    09032016000000000001100                                        01          0ZAZ6      
0330001300028B   100062816250644                              00000                                                  00000000  090320160000000000011000000000000000000000000000000000000000000000000000000000000000000                          
0330001300029A3337001040391600013000022306 LUCAS RUAN FERNANDES NUNES    1004035000102725    09032016BRL0000000000000000000000000010861004035000102725    09032016000000000001086                                        01          0ZAZ6      
0330001300030B   100002441424084                              00000                                                  00000000  090320160000000000010860000000000000000000000000000000000000000000000000000000000000000                          
0330001300031A3337003410870100000000334404 CALINDO RODRIGUES DA SILVA    1004030000100313    09032016BRL0000000000000000000000000221451004030000100313    09032016000000000022145                                        01          0ZAZ6      
0330001300032B   100060898011787                              00000                                                  00000000  090320160000000000221450000000000000000000000000000000000000000000000000000000000000000                          
0330001300033A3337001040401000013000423995 MARIO FRATIC BACIC            1004030000100347    09032016BRL0000000000000000000000000215691004030000100347    09032016000000000021569                                        01          0ZAZ6      
0330001300034B   100068852983872                              00000                                                  00000000  090320160000000000215690000000000000000000000000000000000000000000000000000000000000000                          
0330001300035A3337000010293500000000228087 GINES CARLOS LIRIA            1004030000100735    09032016BRL0000000000000000000000000155271004030000100735    09032016000000000015527                                        01          0ZAZ6      
0330001300036B   100028113278869                              00000                                                  00000000  090320160000000000155270000000000000000000000000000000000000000000000000000000000000000                          
0330001300037A3337003410966300000000083062 APARECIDO GERALDO ARAUJO      1004030000101407    09032016BRL0000000000000000000000000116161004030000101407    09032016000000000011616                                        01          0ZAZ6      
0330001300038B   100007810043811                              00000                                                  00000000  090320160000000000116160000000000000000000000000000000000000000000000000000000000000000                          
0330001300039A3337002370219400001000205729 AVERALDO NUNES PEREIRA        1004030000102017    09032016BRL0000000000000000000000000096801004030000102017    09032016000000000009680                                        01          0ZAZ6      
0330001300040B   100096325666534                              00000                                                  00000000  090320160000000000096800000000000000000000000000000000000000000000000000000000000000000                          
0330001300041A3337001040040600001000107722 JOSE ARILDO DE LIMA           1004030000102165    09032016BRL0000000000000000000000000093891004030000102165    09032016000000000009389                                        01          0ZAZ6      
0330001300042B   100064827364915                              00000                                                  00000000  090320160000000000093890000000000000000000000000000000000000000000000000000000000000000                          
0330001300043A3337000010459800000000210447 ANTONIO APARECIDO PEREIRA RODR1004030000102525    09032016BRL0000000000000000000000000086461004030000102525    09032016000000000008646                                        01          0ZAZ6      
0330001300044B   100073091367134                              00000                                                  00000000  090320160000000000086460000000000000000000000000000000000000000000000000000000000000000                          
0330001300045A3337001040345300001000201847 PAULO OLIVEIRA DOS SANTOS     1004031000100013    09032016BRL0000000000000000000000000080961004031000100013    09032016000000000008096                                        01          0ZAZ6      
0330001300046B   100026691299000                              00000                                                  00000000  090320160000000000080960000000000000000000000000000000000000000000000000000000000000000                          
0330001300047A3337001040204700013000615629 LEVY SILVA DE OLIVEIRA        1004031000100549    09032016BRL0000000000000000000000000072161004031000100549    09032016000000000007216                                        01          0ZAZ6      
0330001300048B   100005654824406                              00000                                                  00000000  090320160000000000072160000000000000000000000000000000000000000000000000000000000000000                          
0330001300049A3337003990067200000000534738 SAMUEL AMANCIO DOS SANTOS     1004031000101365    09032016BRL0000000000000000000000000062651004031000101365    09032016000000000006265                                        01          0ZAZ6      
0330001300050B   100067939791915                              00000                                                  00000000  090320160000000000062650000000000000000000000000000000000000000000000000000000000000000                          
0330001300051A3337002370011300000000079855 JESUS MANOEL VICENTE          1004031000101467    09032016BRL0000000000000000000000000061601004031000101467    09032016000000000006160                                        01          0ZAZ6      
0330001300052B   100025081979805                              00000                                                  00000000  090320160000000000061600000000000000000000000000000000000000000000000000000000000000000                          
0330001300053A3337002370631600000000001953 WESLEY FERREIRA MARCOS        1004031000101581    09032016BRL0000000000000000000000000060371004031000101581    09032016000000000006037                                        01          0ZAZ6      
0330001300054B   100031479884812                              00000                                                  00000000  090320160000000000060370000000000000000000000000000000000000000000000000000000000000000                          
0330001300055A3337003410160400000000018158 JOSE PINHEIRO DE ARAUJO       1004031000101903    09032016BRL0000000000000000000000000057331004031000101903    09032016000000000005733                                        01          0ZAZ6      
0330001300056B   100073208922868                              00000                                                  00000000  090320160000000000057330000000000000000000000000000000000000000000000000000000000000000                          
0330001300057A3337001040061900023000087410 DANIEL DE SOUSA BRIGIDO MAIA  1004031000102375    09032016BRL0000000000000000000000000052901004031000102375    09032016000000000005290                                        01          0ZAZ6      
0330001300058B   100004403285350                              00000                                                  00000000  090320160000000000052900000000000000000000000000000000000000000000000000000000000000000                          
0330001300059A3337001040109400001000231979 MARCOS DA SILVA PEREIRA       1004031000102695    09032016BRL0000000000000000000000000050691004031000102695    09032016000000000005069                                        01          0ZAZ6      
0330001300060B   100007753504789                              00000                                                  00000000  090320160000000000050690000000000000000000000000000000000000000000000000000000000000000                          
0330001300061A3337001040185100010009015904 JOAO PAULO CHAGAS             1004033000100109    09032016BRL0000000000000000000000000033701004033000100109    09032016000000000003370                                        01          0ZAZ6      
0330001300062B   100020641079087                              00000                                                  00000000  090320160000000000033700000000000000000000000000000000000000000000000000000000000000000                          
0330001300063A3337001040136800001000232575 JOSE MARIO DA SILVA QUEIROZ   1004033000100695    09032016BRL0000000000000000000000000031421004033000100695    09032016000000000003142                                        01          0ZAZ6      
0330001300064B   100002262369860                              00000                                                  00000000  090320160000000000031420000000000000000000000000000000000000000000000000000000000000000                          
0330001300065A3337000010289700000000058181 FABIANO LUIZ DOS SANTOS       1004033000100825    09032016BRL0000000000000000000000000030801004033000100825    09032016000000000003080                                        01          0ZAZ6      
0330001300066B   100012705145800                              00000                                                  00000000  090320160000000000030800000000000000000000000000000000000000000000000000000000000000000                          
0330001300067A3337001040019800001000330570 EDSON TORQUATO                1004033000100843    09032016BRL0000000000000000000000000030801004033000100843    09032016000000000003080                                        01          0ZAZ6      
0330001300068B   100024505870715                              00000                                                  00000000  090320160000000000030800000000000000000000000000000000000000000000000000000000000000000                          
0330001300069A3337003410883000000000335249 MARIO SILVA DE AZEVEDO        1004033000100945    09032016BRL0000000000000000000000000030711004033000100945    09032016000000000003071                                        01          0ZAZ6      
0330001300070B   100046083227704                              00000                                                  00000000  090320160000000000030710000000000000000000000000000000000000000000000000000000000000000                          
0330001300071A3337001040346000001000218497 JORGE LUIS FERREIRA ALVES     1004033000101125    09032016BRL0000000000000000000000000029921004033000101125    09032016000000000002992                                        01          0ZAZ6      
0330001300072B   100026312000044                              00000                                                  00000000  090320160000000000029920000000000000000000000000000000000000000000000000000000000000000                          
0330001300073A3337003410693300000000079219 ALEXANDRE BENITES DE VARGAS   1004033000101153    09032016BRL0000000000000000000000000029791004033000101153    09032016000000000002979                                        01          0ZAZ6      
0330001300074B   100000053463048                              00000                                                  00000000  090320160000000000029790000000000000000000000000000000000000000000000000000000000000000                          
0330001300075A3337003410035000000000473724 IVAN NEVES                    1004033000101193    09032016BRL0000000000000000000000000029661004033000101193    09032016000000000002966                                        01          0ZAZ6      
0330001300076B   100044441444834                              00000                                                  00000000  090320160000000000029660000000000000000000000000000000000000000000000000000000000000000                          
0330001300077A3337003410888100000000056629 MARCO ANTONIO OLIVEIRA DA SILV1004033000101337    09032016BRL0000000000000000000000000029041004033000101337    09032016000000000002904                                        01          0ZAZ6      
0330001300078B   100092068022087                              00000                                                  00000000  090320160000000000029040000000000000000000000000000000000000000000000000000000000000000                          
0330001300079A3337001040061900013000244152 DIOGE NUNES MONTEIRO          1004033000101623    09032016BRL0000000000000000000000000028161004033000101623    09032016000000000002816                                        01          0ZAZ6      
0330001300080B   100063792893304                              00000                                                  00000000  090320160000000000028160000000000000000000000000000000000000000000000000000000000000000                          
0330001300081A3337001040044500013000101200 EDSON DA SILVA NUNES          1004033000101899    09032016BRL0000000000000000000000000027191004033000101899    09032016000000000002719                                        01          0ZAZ6      
0330001300082B   100033458634053                              00000                                                  00000000  090320160000000000027190000000000000000000000000000000000000000000000000000000000000000                          
0330001300083A3337000040018900000000366426 ANTONIO CARLOS AZEVEDO DE SOUS1004033000102175    09032016BRL0000000000000000000000000026401004033000102175    09032016000000000002640                                        01          0ZAZ6      
0330001300084B   100063114380387                              00000                                                  00000000  090320160000000000026400000000000000000000000000000000000000000000000000000000000000000                          
0330001300085A3337003890016400000010161661 RENATO JOSE DE FARIAS         1004033000102403    09032016BRL0000000000000000000000000025781004033000102403    09032016000000000002578                                        01          0ZAZ6      
0330001300086B   100084134950678                              00000                                                  00000000  090320160000000000025780000000000000000000000000000000000000000000000000000000000000000                          
0330001300087A3337003410917700000000140093 JADER AQUINO DE SOUZA         1004034000100439    09032016BRL0000000000000000000000000023231004034000100439    09032016000000000002323                                        01          0ZAZ6      
0330001300088B   100008902981738                              00000                                                  00000000  090320160000000000023230000000000000000000000000000000000000000000000000000000000000000                          
0330001300089A3337000410062400003503392808 CRISTIANO LUIS VITT           1004034000100625    09032016BRL0000000000000000000000000022641004034000100625    09032016000000000002264                                        01          0ZAZ6      
0330001300090B   100069417059068                              00000                                                  00000000  090320160000000000022640000000000000000000000000000000000000000000000000000000000000000                          
0330001300091A3337001040043600013001004789 JEFFERSON ERMEL               1004034000100689    09032016BRL0000000000000000000000000022441004034000100689    09032016000000000002244                                        01          0ZAZ6      
0330001300092B   100081775857034                              00000                                                  00000000  090320160000000000022440000000000000000000000000000000000000000000000000000000000000000                          
0330001300093A3337003410733600000000163048 REINALDO PEREIRA DUTRA        1004034000100759    09032016BRL0000000000000000000000000022181004034000100759    09032016000000000002218                                        01          0ZAZ6      
0330001300094B   100068879210068                              00000                                                  00000000  090320160000000000022180000000000000000000000000000000000000000000000000000000000000000                          
0330001300095A3337000010059200000000114561 TIAGO DUARTE MELO             1004034000100821    09032016BRL0000000000000000000000000022001004034000100821    09032016000000000002200                                        01          0ZAZ6      
0330001300096B   100008360665702                              00000                                                  00000000  090320160000000000022000000000000000000000000000000000000000000000000000000000000000000                          
0330001300097A3337001040004500013000005921 CARLOS ALBERTO FALCAO DA ROCHA1004034000101293    09032016BRL0000000000000000000000000021001004034000101293    09032016000000000002100                                        01          0ZAZ6      
0330001300098B   100003881997415                              00000                                                  00000000  090320160000000000021000000000000000000000000000000000000000000000000000000000000000000                          
0330001300099A3337000410083100003500487700 RUDIERI CRISTIANO DE SOUZA    1004034000101561    09032016BRL0000000000000000000000000020241004034000101561    09032016000000000002024                                        01          0ZAZ6      
0330001300100B   100092174280000                              00000                                                  00000000  090320160000000000020240000000000000000000000000000000000000000000000000000000000000000                          
0330001300101A3337003410224700000000213560 OSEIAS DE PAULA SANTOS        1004034000101845    09032016BRL0000000000000000000000000019451004034000101845    09032016000000000001945                                        01          0ZAZ6      
0330001300102B   100021835514880                              00000                                                  00000000  090320160000000000019450000000000000000000000000000000000000000000000000000000000000000                          
0330001300103A3337000040018900010000223154 JOSE AUGUSTO SANTOS QUEIROZ   1004034000102075    09032016BRL0000000000000000000000000018801004034000102075    09032016000000000001880                                        01          0ZAZ6      
0330001300104B   100016867645372                              00000                                                  00000000  090320160000000000018800000000000000000000000000000000000000000000000000000000000000000                          
0330001300105A3337000040000500000000226628 LUIZ CARLOS DOS SANTOS PAULINO1004034000102153    09032016BRL0000000000000000000000000018581004034000102153    09032016000000000001858                                        01          0ZAZ6      
0330001300106B   100004131782502                              00000                                                  00000000  090320160000000000018580000000000000000000000000000000000000000000000000000000000000000                          
0330001300107A3337001040416100013000054096 ALEX CANDIDO FLORENCIO        1004034000102223    09032016BRL0000000000000000000000000018391004034000102223    09032016000000000001839                                        01          0ZAZ6      
0330001300108B   100009350593777                              00000                                                  00000000  090320160000000000018390000000000000000000000000000000000000000000000000000000000000000                          
0330001300109A3337003410058700000000027084 ALMIR SANTORIO                1004034000102551    09032016BRL0000000000000000000000000017601004034000102551    09032016000000000001760                                        01          0ZAZ6      
0330001300110B   100014044919615                              00000                                                  00000000  090320160000000000017600000000000000000000000000000000000000000000000000000000000000000                          
0330001300111A3337001040003500013002399752 GERSON CARLOS DA SILVA        1004034000102553    09032016BRL0000000000000000000000000017601004034000102553    09032016000000000001760                                        01          0ZAZ6      
0330001300112B   100096740450404                              00000                                                  00000000  090320160000000000017600000000000000000000000000000000000000000000000000000000000000000                          
0330001300113A3337002370286300000000200190 EZEQUIEL DOS SANTOS DA SILVA  1004034000102639    09032016BRL0000000000000000000000000017471004034000102639    09032016000000000001747                                        01          0ZAZ6      
0330001300114B   100028953648858                              00000                                                  00000000  090320160000000000017470000000000000000000000000000000000000000000000000000000000000000                          
0330001300115A3337002370011700000001015672 DANIEL CONSTANTINO            1004034000102669    09032016BRL0000000000000000000000000017341004034000102669    09032016000000000001734                                        01          0ZAZ6      
0330001300116B   100028262419820                              00000                                                  00000000  090320160000000000017340000000000000000000000000000000000000000000000000000000000000000                          
0330001300117A3337002370092200000008525242 ROBSON NASCIMENTO             1004036000200039    09032016BRL0000000000000000000000000010651004036000200039    09032016000000000001065                                        01          0ZAZ6      
0330001300118B   100016630919866                              00000                                                  00000000  090320160000000000010650000000000000000000000000000000000000000000000000000000000000000                          
0330001300119A3337003410746500000000073042 JORGE LUIZ DOS SANTOS         1004036000200121    09032016BRL0000000000000000000000000010561004036000200121    09032016000000000001056                                        01          0ZAZ6      
0330001300120B   100025186256072                              00000                                                  00000000  090320160000000000010560000000000000000000000000000000000000000000000000000000000000000                          
0330001300121A3337003410820500000000136230 MARCOS RICARDO RABELLO THOMAZ 1004036000200359    09032016BRL0000000000000000000000000009941004036000200359    09032016000000000000994                                        01          0ZAZ6      
0330001300122B   100030131603817                              00000                                                  00000000  090320160000000000009940000000000000000000000000000000000000000000000000000000000000000                          
0330001300123A3337003410006600000000343278 DARILIO MOREIRA DOS SANTOS    1004036000200519    09032016BRL0000000000000000000000000009591004036000200519    09032016000000000000959                                        01          0ZAZ6      
0330001300124B   100027718168816                              00000                                                  00000000  090320160000000000009590000000000000000000000000000000000000000000000000000000000000000                          
0330001300125A3337001040307900023000007720 ANDRE MARCIO DA SILVA SEABRA  1004036000200763    09032016BRL0000000000000000000000000008801004036000200763    09032016000000000000880                                        01          0ZAZ6      
0330001300126B   100051089270291                              00000                                                  00000000  090320160000000000008800000000000000000000000000000000000000000000000000000000000000000                          
0330001300127A3337000010035000000000330329 KENIO MOTA DA SILVA           1004032000100291    09032016BRL0000000000000000000000000047421004032000100291    09032016000000000004742                                        01          0ZAZ6      
0330001300128B   100080371280168                              00000                                                  00000000  090320160000000000047420000000000000000000000000000000000000000000000000000000000000000                          
0330001300129A3337003410788700000000471527 ANDERSON DE CARVALHO JOTA     1004032000100941    09032016BRL0000000000000000000000000043381004032000100941    09032016000000000004338                                        01          0ZAZ6      
0330001300130B   100013238369857                              00000                                                  00000000  090320160000000000043380000000000000000000000000000000000000000000000000000000000000000                          
0330001300131A3337003410693300000000057108 FABIANO BAPTISTA SALVADOR     1004032000101277    09032016BRL0000000000000000000000000041461004032000101277    09032016000000000004146                                        01          0ZAZ6      
0330001300132B   100000031393012                              00000                                                  00000000  090320160000000000041460000000000000000000000000000000000000000000000000000000000000000                          
0330001300133A3337002370076400000000014621 SANDRA REGINA DE SANTANA ALVES1004032000101325    09032016BRL0000000000000000000000000041271004032000101325    09032016000000000004127                                        01          0ZAZ6      
0330001300134B   100010707366860                              00000                                                  00000000  090320160000000000041270000000000000000000000000000000000000000000000000000000000000000                          
0330001300135A3337003410027100000000028821 FRANCISCO CARLOS TEIXEIRA PICA1004032000102179    09032016BRL0000000000000000000000000036871004032000102179    09032016000000000003687                                        01          0ZAZ6      
0330001300136B   100073430315700                              00000                                                  00000000  090320160000000000036870000000000000000000000000000000000000000000000000000000000000000                          
0330001300137A3337003410094500000000546968 MARCELO LIMA CORREA           1004032000102747    09032016BRL0000000000000000000000000034411004032000102747    09032016000000000003441                                        01          0ZAZ6      
0330001300138B   100058060530402                              00000                                                  00000000  090320160000000000034410000000000000000000000000000000000000000000000000000000000000000                          
03300015         000140000000000000265776000000000000000000030309                                                                                                                                                                               
03399999         000001000142000000

**Comment by andersondanilo** [comment]
No momento, para o Santander, este projeto suporta somente o formato CNAB 240.
Também verifiquei que este formato não é o CNAB 400.

Este retorno é referente à boletos? Se for você pode tentar ver se o teu banco te fornece o arquivo na versão CNAB 240.
