### ISSUE TITLE
Remessa Banco do Estado do Rio Grande do Sul (Banrisul)

### ISSUE THREAD

**Issue by MrjGeek** [andersondanilo/CnabPHP#44]
Olá, alguém já implementou para o banco Banrisul, é um dos bancos mais usados no meu estado e estou precisando para implementar em meu projeto.
Obrigado.
Se alguém se disponibilizar segue link da documentação.
https://www.banrisul.com.br/bob/data/CobrancaEletronicaBanrisul_layout_pdr_Febraban400_vrs09022009.pdf

**Comment by diego-vieira** [comment]
@MrjGeek faz um fork, implementa e manda um PR.
