### ISSUE TITLE
Remessa CNAB 240 SIGCB

### ISSUE THREAD

**Issue by willten** [andersondanilo/CnabPHP#45]
Olá pessoal, tudo bem? 

não sou muito familiarizado com O.O. ... e gostaria de saber se alguém pode me auxiliar na implementação da criação de Remessa para Caixa 240 ? como proceder para enviar vários boletos ao mesmo tempo ??

**Comment by Rogeriociatecnet** [comment]
Bom dia, vc deve repetir $arquivo->insertDetalhe(array(dodos do boleto) para cada boleto que quizer adicionar.
