### ISSUE TITLE
Gerando arquivo de remessa CEF 240

### ISSUE THREAD

**Issue by ederlopes** [andersondanilo/CnabPHP#47]
Estou tentando gerar um arquivo de remessa para o CEF mais ele da o seguinte erro ...

Fatal error: Uncaught Exception: Configuração "codigo_cedente" need to be set in C:\wamp64\www\remessabanco\vendor\andersondanilo\cnab_php\src\Cnab\Remessa\Cnab400\Arquivo.php on line 53

 ja alimentei as configurações com este codigo e ele gera varios outros erros

Fatal error: Uncaught InvalidArgumentException: field 'codigo_cedente' dont exists in C:\wamp64\www\remessabanco\vendor\andersondanilo\cnab_php\src\Cnab\Format\Linha.php on line 15

segue config

$arquivo->configure(array(
    'data_geracao'  => new DateTime(),
    'data_gravacao' => new DateTime(), 
    'nome_fantasia' => 'Nome Fantasia da sua empresa', // seu nome de empresa
    'razao_social'  => 'Razão social da sua empresa',  // sua razão social
    'cnpj'          => '111', // seu cnpj completo
    'banco'         => $codigo_banco, //código do banco
    'logradouro'    => 'Logradouro da Sua empresa',
    'numero'        => 'Número do endereço',
    'bairro'        => 'Bairro da sua empresa', 
    'cidade'        => 'Cidade da sua empresa',
    'uf'            => 'Sigla da cidade, ex SP',
    'cep'           => 'CEP do endereço da sua cidade',
    'agencia'       => '1111', 
    'conta'         => '22222', // número da conta
    'operacao'     => '1', // digito da conta
    'codigo_cedente'     => '1979200', // digito da conta
    'codigo_cedente_dac'     => '10', // digito da conta
));

**Comment by Rogeriociatecnet** [comment]
Bom dia.. olhando seu post percebi que esta usando o arquivo path "C:\wamp64\www\remessabanco\vendor\andersondanilo\cnab_php\src\Cnab\Remessa\Cnab400\Arquivo.php on line 53" indica Cnab400, nao seria esse o problema

**Comment by ederlopes** [comment]
Colei o cnab do Bradesco ..no seu a CEF funciona? poderia me mandar um
Fonte com um exemplo atualizado por favor desde já agradeço
Em 01/04/2016 12:33, "Rogerio Muniz" <notifications@github.com> escreveu:

**Comment by Rogeriociatecnet** [comment]
Então eu tambem fiz isso que você fez, mas pesquisando, descobri a CEF não implementou o arquivo de 400 colunas entao deveria usar o layout de 240 colunas, o meu inda nao esta funcionando, estou enroscado em outro campo mas vi a outra issue que ja tem solução,
`$arquivo  = new Cnab\Remessa\Cnab240\Arquivo($codigo_banco);
		
		$arquivo->configure(array(
			'data_geracao'  => new DateTime(),
			'data_gravacao' => new DateTime(), 
			'nome_fantasia' => $empresa->empresas_nomefantasia, // seu nome de empresa
			'razao_social'  => $empresa->empresas_razaosocial,  // sua razão social
			'cnpj'          => $empresa->empresas_cnpjcpf, // seu cnpj completo
			'banco'         => $codigo_banco, //código do banco
			'logradouro'    => $empresa->empresas_endereco,
			'numero'        => $empresa->empresas_numero,
			'bairro'        => $empresa->empresas_bairro, 
			'cidade'        => $empresa->cidades_nome,
			'uf'            => $empresa->empresas_uf,
			'cep'           => $empresa->empresas_cep,
			'agencia'       => $agencia[0], 
			'agencia_dv'    => $agencia[1], 
			'conta'         => $conta[0], // número da conta
			'conta_dac'     => $conta[1], // digito da conta
			'operacao'      => $conta[1], // operacao da conta
			'codigo_cedente'     => $cod_cedente[0], 
			'codigo_cedente_dac'     => $cod_cedente[1], // digito do cedente
			'codigo_cedente_dv'     => $cod_cedente[1], // digito do cedente
			'numero_sequencial_arquivo'     => $lastInsert['lastInsertId'], // digito da conta
		));
		
			$sacado_tipo = $locatario->locatarios_pfpj=='F'?'cpf':'cnpj';
			$arquivo->insertDetalhe(array(
				'codigo_ocorrencia' => $object->boletos_acoes_codigo, // 1 = Entrada de título, futuramente poderemos ter uma constante
				'nosso_numero'      => $object->boletos_codigo,
				'numero_documento'  => $object->boletos_codigo.$object->boletos_parcela,
				'codigo_cedente'    => $cod_cedente[0], // digito da conta
				'codigo_cedente_dv' => $cod_cedente[1], // digito do cedente
				'carteira'          => $carteira->carteiras_nome,
				'registrado'        => $carteira->carteiras_registro,
				'aceite'            => 'N',
				'especie'           => $object->boletos_especie, // Você pode consultar as especies Cnab\Especie
				'valor'             => $object->getUnformated("boletos_valor"), // Valor do boleto
				'instrucao1'        => 2, // 1 = Protestar com (Prazo) dias, 2 = Devolver após (Prazo) dias, futuramente poderemos ter uma constante
				'instrucao2'        => 0, // preenchido com zeros
				'sacado_nome'       => $locatario->locatarios_nome, // O Sacado é o cliente, preste atenção nos campos abaixo
				'sacado_tipo'       => $sacado_tipo, //campo fixo, escreva 'cpf' (sim as letras cpf) se for pessoa fisica, cnpj se for pessoa juridica
				'sacado_cpf'        => $locatario->locatarios_cnpjcpf,
				'sacado_logradouro' => $locatario->enderecos[0]->enderecos_logradouro,
				'sacado_bairro'     => $locatario->enderecos[0]->enderecos_bairro,
				'sacado_cep'        => $locatario->enderecos[0]->enderecos_cep, // sem hífem
				'sacado_cidade'     => $locatario->enderecos[0]->cidades_nome,
				'sacado_uf'         => $locatario->enderecos[0]->enderecos_uf,
				'data_vencimento'   => new DateTime($object->boletos_data_venc),
				'data_cadastro'     => new DateTime(date("Y-m-d")),
				'juros_de_um_dia'     => $object->getUnformated('boletos_juro_dia'), // Valor do juros de 1 dia'
				'data_desconto'       => new DateTime($object->boletos_data_desc),
				'valor_desconto'      => $object->getUnformated('boletos_vlr_desc'), // Valor do desconto
				'prazo'               => $object->boletos_prazo, // prazo de dias para o cliente pagar após o vencimento
				'taxa_de_permanencia' => $object->boletos_tx_permanencia, //00 = Acata Comissão por Dia (recomendável), 51 Acata Condições de Cadastramento na CAIXA
				'mensagem'            => $object->boletos_mensagem,
				'data_multa'          => new DateTime($object->boletos_data_multa), // data da multa
				'valor_multa'         => $object->getUnformated('boletos_vlr_multa'), // valor da multa
			));        
		}
		echo $arquivo->getText();`

**Comment by Rogeriociatecnet** [comment]
A saber onde estou enroscado é 'codigo_cedente_dv' https://github.com/andersondanilo/CnabPHP/issues/32

**Comment by ederlopes** [comment]
Pois e ...como faço para pegar a última issue?
Em 01/04/2016 14:21, "Rogerio Muniz" <notifications@github.com> escreveu:

**Comment by Rogeriociatecnet** [comment]
Então estou implementando exatamente a mesma coisa que você agora, fui fuçando no código até gerar o txt, so nao sei dizer se esta correto e se vai passar no banco mas, o meu sistema ainda vai demorar um pouco para entrar em produção e pode testar mas posso criar um fork com essas alteração, ai vc copia e testa. ok?

**Comment by ederlopes** [comment]
ok blz espero o seu fork

Em 1 de abril de 2016 16:51, Rogerio Muniz <notifications@github.com>
escreveu:

**Comment by foccos** [comment]
Bom dia, estou com uma necessidade:

Já possuo o modulo de geração de boletos da CEF homologado em PHP. 

Preciso criar as remessas para que o usuário possa fazer download do arquivo e enviar ao banco.

No sistema é gerado vários boletos de uma única vez com dados fixos de teste, sendo assim já implementei o código em anexo e o sistema está criando o arquivo de remessa com um único boleto.

Poderia me informar um passo a passo para fazer isso?





[criar_remessa.txt](https://github.com/andersondanilo/CnabPHP/files/201366/criar_remessa.txt)

**Comment by Rctnet** [comment]
Boa noite ederlopes o meu fork nao vai sair, pois criei um projeto novo e o primeiro layout que disponibilizo é o cnab240 SIGCB caixa, caso queira dar uma olhada entre no meu perfil e encontrara meu projeto, se tiver alguma duvida pode contar comigo

**Comment by ederlopes** [comment]
Boa noite Rogério vc conseguiu homologar junto a caixa o arquivo no layout
240? Caso sim no seu perfil tem este código de geração do arquivo? Desde já
agradeço o empenho e compartilhamento de informação...
Em 09/04/2016 21:00, "Rogerio Muniz" <notifications@github.com> escreveu:

**Comment by Rctnet** [comment]
Na verdade ainda não homologuei, comecei a codificar a uma semana e vou poder homologar só daqui a um mês, quando o meu sistema começa a funcionar para valer. mas case se interesse pode me ajudar testando e codificando, sei como é difícil encontrar material e código que funcione adequadamente e não vou para tão cedo de mexer nesse projeto, a caixa trabalha com três Layouts cnb240 um SIACC que não é usado para boletos, só para  pagamentos,(mas poderá ter suporte), o SIGCB que é o mais comum e é o que esta disponível no meu perfil, e o SICOB que também é para boletos, veja qual você vai usar e me avise estive olhando o SICOB por cima e é quase igual ao SIGCB e sim no meu perfil tem o código de geração. tudo comentado e de fácil entendimento.

**Comment by foccos** [comment]
Estou tentando rodar com o SIGCB, me envie o link do seu que esta rodando.

 

 

Atenciosamente,
 
Vinícius Marques  |  Empreendedor
Fone: 34 3321.5060 |34 8867.1187
 <http://www.iTurn.com.br> www.iTurn.com.br |  <http://www.Foccosti.com.br> www.Foccosti.com.br 
      

 

De: Rogerio Muniz [mailto:notifications@github.com] 
Enviada em: sábado, 9 de abril de 2016 21:34
Para: andersondanilo/CnabPHP
Cc: foccos
Assunto: Re: [andersondanilo/CnabPHP] Gerando arquivo de remessa CEF 240 (#47)

 

Na verdade ainda não homologuei, comecei a codificar a uma semana e vou poder homologar só daqui a um mês, quando o meu sistema começa a funcionar para valer. mas case se interesse pode me ajudar testando e codificando, sei como é difícil encontrar material e código que funcione adequadamente e não vou para tão cedo de mexer nesse projeto, a caixa trabalha com três Layouts cnb240 um SIACC que não é usado para boletos, só para pagamentos,(mas poderá ter suporte), o SIGCB que é o mais comum e é o que esta disponível no meu perfil, e o SICOB que também é para boletos, veja qual você vai usar e me avise estive olhando o SICOB por cima e é quase igual ao SIGCB e sim no meu perfil tem o código de geração. tudo comentado e de fácil entendimento.

**Comment by andrelimeira** [comment]
Porque não foi feita uma PR aqui para atualizar esse repositório e criou outro repositório ? O autor do projeto não está mais ativo é isso ?

Abraço

**Comment by Rctnet** [comment]
Boa noite André, criei outro projeto por achar, no meu entendimento que o projeto em questão não atendia as minhas necessidades, no meu caso a abordagem foi totalmente diferente, não sendo possível compatibilizar com esse projeto.

**Comment by almando** [comment]
Alguém ai já implementou o processamento do retorno do arquivo da caixa, cnab 240?

**Comment by luizjustino** [comment]
Editem Arquivo.php e troquem null por 'sigcb' :
    public function __construct($codigo_banco, $layoutVersao = 'sigcb')

**Comment by muriloc4** [comment]
O Pessoal da Validação da CAIXA mandou os seguintes erros
12.3P,
Carteira deveria ser
Cód Devolução Deveria ser 1 ou 2
Titulo com Nosso Numero de Registrada marcado como Sem Registro na posição 41
Titulo com Nosso Numero indicando impressão CAIXA, mas marcado na posição 61 como cedente.

**Comment by foccos** [comment]
Você vai precisar verificar exatamente as posições do seu arquivo de remessa e comparar as posições com erro.

 

Atenciosamente,
 
Vinícius Marques  |  CEO
Fone: 34 3321.5060 |34 98867.1187
Skype: vini_3020
 <http://www.iturn.com.br/> www.iTurn.com.br |  <http://www.foccosti.com.br/> www.Foccosti.com.br 
      

 

De: muriloc4 [mailto:notifications@github.com] 
Enviada em: segunda-feira, 5 de dezembro de 2016 13:52
Para: andersondanilo/CnabPHP
Cc: foccos; Comment
Assunto: Re: [andersondanilo/CnabPHP] Gerando arquivo de remessa CEF 240 (#47)

 

O Pessoal da Validação da CAIXA mandou os seguintes erros
12.3P,
Carteira deveria ser
Cód Devolução Deveria ser 1 ou 2
Titulo com Nosso Numero de Registrada marcado como Sem Registro na posição 41
Titulo com Nosso Numero indicando impressão CAIXA, mas marcado na posição 61 como cedente.

**Comment by pleiadess** [comment]
Pessoal, 

A confusão toda é pq o link https://github.com/andersondanilo/CnabPHP/wiki/Criando-um-arquivo-de-remessa mostra um exemplo pro Itau e para CEF precisamos de mais campos.

Usem isso:

<?php
include 'vendor/autoload.php';

$codigo_banco = Cnab\Banco::CEF;
$arquivo = new Cnab\Remessa\Cnab240\Arquivo($codigo_banco);
$arquivo->configure(array(
    'data_geracao'  => new DateTime(),
    'data_gravacao' => new DateTime(), 
    'nome_fantasia' => 'Nome Fantasia da sua empresa', // seu nome de empresa
    'razao_social'  => 'Razão social da sua empresa',  // sua razão social
    'cnpj'          => '111', // seu cnpj completo
    'banco'         => $codigo_banco, //código do banco
    'logradouro'    => 'Logradouro da Sua empresa',
    'numero'        => 'Número do endereço',
    'bairro'        => 'Bairro da sua empresa', 
    'cidade'        => 'Cidade da sua empresa',
    'uf'            => 'Sigla da cidade, ex SP',
    'cep'           => 'CEP do endereço da sua cidade',
    'agencia'       => '1111', 
    'conta'         => '22222', // número da conta
    'conta_dac'     => '2', // digito da conta
    'codigo_cedente' => '123123',
    'codigo_cedente_dv' => '4',
	'agencia_dv' => '3',
	'operacao' => '012',
	'numero_sequencial_arquivo' => 1,
));

// você pode adicionar vários boletos em uma remessa
$arquivo->insertDetalhe(array(
    'codigo_ocorrencia' => 1, // 1 = Entrada de título, futuramente poderemos ter uma constante
    'nosso_numero'      => '1234567',
    'numero_documento'  => '1234567',
    'carteira'          => '109',
    'modalidade_carteira' => '21',
    'especie'           => Cnab\Especie::CEF_DUPLICATA_DE_PRESTACAO_DE_SERVICOS, // Você pode consultar as especies Cnab\Especie
	'aceite' => 'N', // "S" ou "N"
	'registrado' => false,
	'valor'             => 100.39, // Valor do boleto
    'instrucao1'        => 2, // 1 = Protestar com (Prazo) dias, 2 = Devolver após (Prazo) dias, futuramente poderemos ter uma constante
    'instrucao2'        => 0, // preenchido com zeros
    'sacado_nome'       => 'Nome do cliente', // O Sacado é o cliente, preste atenção nos campos abaixo
    'sacado_tipo'       => 'cpf', //campo fixo, escreva 'cpf' (sim as letras cpf) se for pessoa fisica, cnpj se for pessoa juridica
    'sacado_cpf'        => '111.111.111-11',
    'sacado_logradouro' => 'Logradouro do cliente',
    'sacado_bairro'     => 'Bairro do cliente',
    'sacado_cep'        => '11111222', // sem hífem
    'sacado_cidade'     => 'Cidade do cliente',
    'sacado_uf'         => 'SP',
    'data_vencimento'   => new DateTime('2014-06-08'),
    'data_cadastro'     => new DateTime('2014-06-01'),
    'juros_de_um_dia'     => 0.10, // Valor do juros de 1 dia'
    'data_desconto'       => new DateTime('2014-06-01'),
    'valor_desconto'      => 10.0, // Valor do desconto
    'prazo'               => 10, // prazo de dias para o cliente pagar após o vencimento
    'taxa_de_permanencia' => '0', //00 = Acata Comissão por Dia (recomendável), 51 Acata Condições de Cadastramento na CAIXA
    'mensagem'            => 'Descrição do boleto',
    'data_multa'          => new DateTime('2014-06-09'), // data da multa
    'valor_multa'         => 10.0, // valor da multa
));

// para salvar
$arquivo->save('cef.txt');

Alem disso a correção do luizjustino tem que ser aplicada:

Editem Arquivo.php e troquem null por 'sigcb' :
public function __construct($codigo_banco, $layoutVersao = 'sigcb')

Fiz assim e finalmente consegui gerar o arquivo.

Homologar é outra história.

**Comment by foccos** [comment]
Boa tarde, eu segui com o projeto e conseguimos homologar CEF.

 

 

 

Atenciosamente,
 
Vinícius Marques  |  CEO
Fone: 34 3321.5060 |34 98867.1187
Skype: vini_3020
 <http://www.iturn.com.br/> www.iTurn.com.br |  <http://www.foccosti.com.br/> www.Foccosti.com.br 
      

 

De: Hyder [mailto:notifications@github.com] 
Enviada em: quarta-feira, 18 de janeiro de 2017 12:10
Para: andersondanilo/CnabPHP
Cc: foccos; Comment
Assunto: Re: [andersondanilo/CnabPHP] Gerando arquivo de remessa CEF 240 (#47)

 

Pessoal,

A confusão toda é pq o link https://github.com/andersondanilo/CnabPHP/wiki/Criando-um-arquivo-de-remessa mostra um exemplo pro Itau e para CEF precisamos de mais campos.

Usem isso:

configure(array( 'data_geracao' => new DateTime(), 'data_gravacao' => new DateTime(), 'nome_fantasia' => 'Nome Fantasia da sua empresa', // seu nome de empresa 'razao_social' => 'Razão social da sua empresa', // sua razão social 'cnpj' => '111', // seu cnpj completo 'banco' => $codigo_banco, //código do banco 'logradouro' => 'Logradouro da Sua empresa', 'numero' => 'Número do endereço', 'bairro' => 'Bairro da sua empresa', 'cidade' => 'Cidade da sua empresa', 'uf' => 'Sigla da cidade, ex SP', 'cep' => 'CEP do endereço da sua cidade', 'agencia' => '1111', 'conta' => '22222', // número da conta 'conta_dac' => '2', // digito da conta 'codigo_cedente' => '123123', 'codigo_cedente_dv' => '4', 'agencia_dv' => '3', 'operacao' => '012', 'numero_sequencial_arquivo' => 1, )); // você pode adicionar vários boletos em uma remessa $arquivo->insertDetalhe(array( 'codigo_ocorrencia' => 1, // 1 = Entrada de título, futuramente poderemos ter uma constante 'nosso_numero' => '1234567', 'numero_documento' => '1234567', 'carteira' => '109', 'modalidade_carteira' => '21', 'especie' => Cnab\Especie::CEF_DUPLICATA_DE_PRESTACAO_DE_SERVICOS, // Você pode consultar as especies Cnab\Especie 'aceite' => 'N', // "S" ou "N" 'registrado' => false, 'valor' => 100.39, // Valor do boleto 'instrucao1' => 2, // 1 = Protestar com (Prazo) dias, 2 = Devolver após (Prazo) dias, futuramente poderemos ter uma constante 'instrucao2' => 0, // preenchido com zeros 'sacado_nome' => 'Nome do cliente', // O Sacado é o cliente, preste atenção nos campos abaixo 'sacado_tipo' => 'cpf', //campo fixo, escreva 'cpf' (sim as letras cpf) se for pessoa fisica, cnpj se for pessoa juridica 'sacado_cpf' => '111.111.111-11', 'sacado_logradouro' => 'Logradouro do cliente', 'sacado_bairro' => 'Bairro do cliente', 'sacado_cep' => '11111222', // sem hífem 'sacado_cidade' => 'Cidade do cliente', 'sacado_uf' => 'SP', 'data_vencimento' => new DateTime('2014-06-08'), 'data_cadastro' => new DateTime('2014-06-01'), 'juros_de_um_dia' => 0.10, // Valor do juros de 1 dia' 'data_desconto' => new DateTime('2014-06-01'), 'valor_desconto' => 10.0, // Valor do desconto 'prazo' => 10, // prazo de dias para o cliente pagar após o vencimento 'taxa_de_permanencia' => '0', //00 = Acata Comissão por Dia (recomendável), 51 Acata Condições de Cadastramento na CAIXA 'mensagem' => 'Descrição do boleto', 'data_multa' => new DateTime('2014-06-09'), // data da multa 'valor_multa' => 10.0, // valor da multa )); // para salvar $arquivo->save('cef.txt'); Alem disso a correção do luizjustino tem que ser aplicada: Editem Arquivo.php e troquem null por 'sigcb' : public function __construct($codigo_banco, $layoutVersao = 'sigcb') Fiz assim e finalmente consegui gerar o arquivo. Homologar é outra história.

**Comment by murilosandiego** [comment]
Só passar 'sigcb' no construtor do arquivo 
$arquivo = new \Cnab\Remessa\Cnab240\Arquivo($codigoBanco, 'sigcb');
