### ISSUE TITLE
Boa tarde Focos 

### ISSUE THREAD

**Issue by ederlopes** [andersondanilo/CnabPHP#48]
Você poderia disponibilizar seu modulo de geração de boleto do CEF? 

em relação a seu arquivo de geração você adaptou a geração para o layout de 400? porque não entendi os arrays abaixo gerados..

$configHeaderArquivo = array (
    "1" => 3,
    "2" => 4,
    "3" => 1,
    "4" => 9,
    "5" => 1,
    "6" => 14,
    "7" => 20,
    "8" => 5,
    "9" => 1,
    "10" => 12,
    "11" => 1,
    "12" => 1,
    "13" => 30,
    "14" => 30,
    "15" => 10,
    "16" => 1,
    "17" => 8,
    "18" => 6,
    "19" => 6,
    "20" => 3,
    "21" => 5,
    "22" => 20,
    "23" => 20,
    "24" => 29,
);

$configTypeHeaderArquivo = array (
    "1" => "num",
    "2" => "num",
    "3" => "num",
    "4" => "str",
    "5" => "num",
    "6" => "num",
    "7" => "str",
    "8" => "num",
    "9" => "str",
    "10" => "num",
    "11" => "str",
    "12" => "str",
    "13" => "str",
    "14" => "str",
    "15" => "str",
    "16" => "num",
    "17" => "num",
    "18" => "num",
    "19" => "num",
    "20" => "num",
    "21" => "num",
    "22" => "str",
    "23" => "str",
    "24" => "str",
);

**Comment by andersondanilo** [comment]
Desconheço este código que você colocou,

Para gerar uma "remessa" de boleto você pode seguir como exemplo o teste unitário:

https://github.com/andersondanilo/CnabPHP/blob/master/tests/Cnab/Remessa/Cnab240/CaixaTest.php

Deste banco (Caixa) só foi implementado o formato de remessa 240
