### ISSUE TITLE
Remessa Sicoob

### ISSUE THREAD

**Issue by clebersonmachi** [andersondanilo/CnabPHP#50]
Gostaria de saber se é possível gerar o arquivo de remessa para o banco sicoob.

Eu gerei o arquivo conforme o modelo abaixo e gerou o arquivo corretamente:

`$arquivo = new Cnab\Remessa\Cnab400\Arquivo($codigo_banco);
$arquivo->configure(array(
    'data_geracao'  => new DateTime(),
    'data_gravacao' => new DateTime(), 
    'nome_fantasia' => 'NOME_FANTASIA', // seu nome de empresa
    'razao_social'  => 'RAZAO_SOCIAL',  // sua razão social
    'cnpj'          => 'CNPJ', // seu cnpj completo
    'banco'         => $codigo_banco, //código do banco
    'logradouro'    => 'meu endereço',
    'numero'        => '318',
    'bairro'        => 'Bela Aliança', 
    'cidade'        => 'Rio do Sul',
    'uf'            => 'SC',
    'cep'           => '89161310',
    'agencia'       => 'xxxx', 
    'conta'         => 'xxxxx', // número da conta
    'conta_dac'     => 'x', // digito da conta
));`

Porém ao importar no sistema cedente do Sicoob ele está informando o seguinte erro:

> O número do cliente descrito no arquivo não corresponde ao configurado no sistema

Alguém poderia me ajudar nesta questão? Existe algum padrão específico para a Sicoob?

Obrigado

**Comment by alandebortolo** [comment]
Boa tarde Cleberson, eu nem consegui gerar no padrão Cnab240 (que é o aceito pelo Sicoob). Quais configurações você usou?

**Comment by wemersonjanuario** [comment]
@clebersonmachi vou implantar Siccob também. Deu tudo certo com o seu? O que tem pra compartilhar?

Obrigado

**Comment by clebersonmachi** [comment]
Bom dia...

Eu fiz uma classe para gerar o arquivo de remessa... consegui fazer apenas para cobrança por enquanto.

Segue o link para visualizar no GitHub: https://github.com/clebersonmachi/BoletoSicoob

Desculpe se eu não utilizei da forma correta, mas esta é a primeira vez que eu utilizo o GitHub para isto. :S

Valeu.

**Comment by clebersonmachi** [comment]
Bom dia pessoal...

Eu corrigi um detalhe na geração do nosso número.
Acredito que agora esteja tudo correto.

**Comment by wemersonjanuario** [comment]
vou fazer um pull request em breve com a implementação do Sicoob cnab400, Homologuei hoje meu fork.
