### ISSUE TITLE
Erro de Instalação

### ISSUE THREAD

**Issue by PlaynowGames** [andersondanilo/CnabPHP#53]
sabem pq da esse erro na hora de instalar?

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package andersondanilo/cnab_php No version set (parsed as 1.0.0) is satisfiable by andersondanilo/cnab_php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by valterlima** [comment]
Qual comando você tentou rodar? Aqui fiz da seguinte forma e deu certo:

1. Criei um diretorio vazio e entrei nele
2. Comando `composer init` e insira as informações do pacote se quiser
3. Comando `composer require `andersondanilo/cnab_php` e ele vai baixar o pacote

**Comment by alamvilalves** [comment]
Deu o mesmo erro comigo, e não consegui resolver com a dica do valterlima!

**Comment by hallyssonweb** [comment]
Estou com o mesmo problema e não consigo resolver.

**Comment by andersondanilo** [comment]
Olá,

Você também pode tentar atualizar o composer com o comando:

`composer self-update`

**Comment by alamvilalves** [comment]
Obg pela resposta. Já estou com a última versão.

You are already using composer version 1.2.0 (stable channel).

**Comment by hallyssonweb** [comment]
Já atualizei o composer e continua do mesmo jeito.

**Comment by adsergio** [comment]
Amigos, tentei também e não consegui. Usando as dicas acima ainda assim não funcionou.

**Comment by andersondanilo** [comment]
Você pode tentar usar a versão 1.3.*

**Comment by burbes** [comment]
Eu inseri a linha

"version": "1.3",

Executei o comando

composer require andersondanilo/cnab_php

e funcionou
