### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by marcelocajaiba** [andersondanilo/CnabPHP#58]
Olá colegas tudo bem !
Estou querendo usar o código para remessa, eu tentei testar no meu wamp e deu erro de página, dai li o documentário do script vi que tem que instalar o composer, mas e no servidor de hospedagem não tem como instalar  o composer e no  servidor linux funciona também?

não encontrei esse arquivo vendor !

Obrigado !

**Comment by andersondanilo** [comment]
Olá Marcelo,

Você pode instalar o composer na sua máquina, instalar o CnabPHP e subir a pasta vendor junto.

O composer só é necessário para fazer o Download do CnabPHP e configurar o autoload.
