### ISSUE TITLE
Problema com caminho do pacote cnab_yaml

### ISSUE THREAD

**Issue by juliolustosa** [andersondanilo/CnabPHP#6]
Sugestão deixar o caminho para o pacote cnab_yaml podendo ser personalizado, eu mesmo uso o framework Laravel

YamlLoad.php - Linha 4
define('CNAB_FORMAT_PATH', dirname(__FILE__).'/../../../vendor/andersondanilo/cnab_yaml');

**Comment by jefersondaniel** [comment]
Havia um problema nesta parte do código, agora o caminho para o cnab_yaml está sendo buscado corretamente. Mesmo assim, esse caminho poderá ser alterado com método \Cnab\Factory::setCnabFormatPath

**Comment by juliolustosa** [comment]
Resolveu, obrigado.
