### ISSUE TITLE
ERRO DE INSTALAÇÃO

### ISSUE THREAD

**Issue by tarifaonline** [andersondanilo/CnabPHP#62]
Problem 1
    - The requested package andersondanilo/cnab_php No version set (parsed as 1.0.0) is satisfiable by andersondanilo/cnab_php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

já tentei usar **composer self-update** , **composer init**
Tentei, todos os tipos não de comandos e não funcionou.

**Comment by andersondanilo** [comment]
No seu caso parece que ele deduziu a versão como 1.0.0, você pode tentar especificar a versão

**Comment by burbes** [comment]
Eu inseri a linha 

"version": "1.3",

Executei o comando

composer require andersondanilo/cnab_php

e funcionou
