### ISSUE TITLE
Significado dos campos Nosso número e Número documento 

### ISSUE THREAD

**Issue by amrigo** [andersondanilo/CnabPHP#67]
Boa noite Anderson

Peço uma orientação, estou montando remessa Banco do Brasil CNAB240,  vi que tem limitação de número de caracteres mas não encontrei ainda o significado do uso deles. 

Teria maiores detalhes do significado deles ? qual campo da remessa que corresponde aos campos do boleto?

$arquivo->insertDetalhe(array(
            'nosso_numero' => '12345',
            'numero_documento' => '12345678',

**Comment by andersondanilo** [comment]
O nosso número é o número do boleto, o número do documento é de uso livre seu. (também é imprimido no boleto, assim como o nosso número)
