### ISSUE TITLE
Homolagação da Caixa Econômica Federal reprovada

### ISSUE THREAD

**Issue by juizmill** [andersondanilo/CnabPHP#68]
Ao fazer a homologação do arquivo remessa, a caixa reprovou porque o nome do banco esta escrito errado, atualmente esta C ECON FEDERAL o coreto seria **CAIXA ECONOMICA FEDERAL**

**Comment by juizmill** [comment]
Acabo de ver que na versão **dev-mater** está coreto, já na versão estável esta errado

**Comment by andersondanilo** [comment]
A versão 1.3.16 já inclui esta e outras alterações
