### ISSUE TITLE
Código correto de retorno de liquidação

### ISSUE THREAD

**Issue by fabioginzel** [andersondanilo/CnabPHP#71]
A função isBaixa esta misturando códigos que não significam baixa de titulo, isto é, são apenas baixados no banco por causa do registro mas não significa que foram pagos

**Comment by andersondanilo** [comment]
Nesse caso acho melhor um outro método só para os códigos de liquidação, pois como o nome do método é "isBaixa" e o nome do código "9" é baixa, ficaria meio sem sentido retirar ele deste método. Ao meu ponto de vista para este caso seria melhor um método isLiquidacao ou algo do tipo.
