### ISSUE TITLE
Remessa Itau CNAB240

### ISSUE THREAD

**Issue by amrigo** [andersondanilo/CnabPHP#74]
Bom dia 
Gostaria de enviar remessa para o Itau. Qual seria o caminho.?
Atualmente após ajustar algumas variáveis vazias tenho 'codigo_cedente' dont be false or null. Em : ROOT\vendors\andersondanilo\cnab_php\src\Cnab\Format\Linha.php line 13

**Comment by andersondanilo** [comment]
No momento não suportamos a remessa do Itaú no formato CNAB240, só o CNAB400
