### ISSUE TITLE
Remessa 400 do Itaú  campo data_mora length '8',  need length 6

### ISSUE THREAD

**Issue by amrigo** [andersondanilo/CnabPHP#77]
Oi 
Estou tentanto rodar a remessa CNAB 400 do Itau parei nesta mensagem :

 '20170108' 'data_mora' have length '8', but field need length 6

Que formato precisa neste campo ? tentei passar este : 20170108

**Comment by amrigo** [comment]
Passei 080117 como saber se é o formato esperado ?

**Comment by fernandodemoraes** [comment]
Segundo o layout:

Campo: DATA DE MORA Posição: 386 à 391 Picture:: 9(06) Conteúdo: DDMMAA

ou seja, 080117

**Comment by amrigo** [comment]
Obrigado Fernando
