### ISSUE TITLE
Nosso número Santander com Digito Verificar

### ISSUE THREAD

**Issue by juliolustosa** [andersondanilo/CnabPHP#8]
O Nosso número do retorno do banco santander está pegando o digito verificar se o nosso número do boleto é 137 na leitura do retorno aparece como 1376. Desde já obrigado.

**Comment by juliolustosa** [comment]
O problema está acontecendo também com a CAIXA ele está pegando uma posição a mais do Nosso Numero do arquivo de retorno. obrigado.

**Comment by andersondanilo** [comment]
Ok, será criada um nova função: "getNossoNumeroSemDv" para manter a compatibilidade com o antigo

**Comment by andersondanilo** [comment]
Eu não estou com tempo esta semana (ou este mês), mas tenha liberdade de fazer as alterações necessárias para o seu uso.

**Comment by juliolustosa** [comment]
Uma dúvida todo nosso número sempre pega o digito verificar ? Obrigado.

**Comment by andersondanilo** [comment]
O itau retorna sem o DV, a partir de agora retornar com o DV será considerado um bug (que acredito que seja o que todos esperávamos).

Commit: 9d4d43c0965b8a9eb6d28a855a00af22993e043c

**Comment by Ronismeiden** [comment]
Percebi que ocorre também com retorno Bradesco. Já foi revisado?
