### ISSUE TITLE
Validação de Layout no Itau CNAB400

### ISSUE THREAD

**Issue by a6publicidade** [andersondanilo/CnabPHP#80]
Fiz a validação do layout CNAB (cobrança) 400 e apresentou os erros abaixo:

Layout: Itaú - Cob. com Registro - CNAB 400
Registro: detalhe
Linha: 2
Posição 157 - Campo: 1a Instrução de Cobrança - Conteúdo do campo fora do conjunto permitido. (2 )
Posição 159 - Campo: 2a Instrução de Cobrança - Conteúdo do campo fora do conjunto permitido. (0 )
Posição 235 - Campo: Nome do Sacado - Conteúdo não pode estar em branco. (em branco)

**Comment by rdenubila** [comment]
Boa tarde!

Tive o mesmo problema dos campos de instrução ao tentar validar no Itaú. Resolvi o problema trocando os valores instrucao1 e instrucao2 por string com dois dígitos, ficou assim:

 'instrucao1' => "05", 
 'instrucao2' => "00",

Os possíveis valores  dessas instruções estão nesse documento, na página 20
http://download.itau.com.br/bankline/layout_cobranca_400bytes_cnab_itau.pdf

**Comment by brjorgedavid** [comment]
@rdenubila Eu estou com o mesmo problema:
 Posição 157 - Campo: 1ª Instrução de Cobrança - Conteúdo do campo fora do conjunto permitido. (66) 

Porém, tentei aplicar a mesma solução que vc usou, mas mesmo assim o problema persiste.
