### ISSUE TITLE
Problema com valor_titulo

### ISSUE THREAD

**Issue by juliolustosa** [andersondanilo/CnabPHP#9]
Arquivo: andersondanilo/cnab_php/src/Cnab/Format/Field.php:52
'Exception' with message ''valor_titulo' have length '27', but field need length 15'

Cnab\Format\Field->set(70.45999999999999)

**Comment by andersondanilo** [comment]
Não consegui reproduzir o erro com este teste unitário
Commit: 9d4d43c0965b8a9eb6d28a855a00af22993e043c.

Por favor faça o pull do projeto e tente executar os testes unitários novamente, se falhar coloque o resultado aqui.

**Comment by juliolustosa** [comment]
Enviei um Pull Request que resolveu o problema.
https://github.com/andersondanilo/CnabPHP/pull/11
